import type { Modul } from "../../lernpfade-data";
const m: Modul = { id: "kk1", title: "KVG Grundlagen", description: "Obligatorische Krankenversicherung, Leistungen, Franchise, Prämien", credits: 30, lektionen: [
  { id: "kk1-1", title: "Das KVG System", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Obligatorische Grundversicherung (OKP)", content: "Seit 1996 Pflicht für alle:", bulletPoints: ["Jede Person mit Wohnsitz in der Schweiz muss versichert sein", "Frist: 3 Monate nach Zuzug/Geburt", "Freie Kassenwahl: Über 50 Krankenkassen in der Schweiz", "Einheitlicher Leistungskatalog: Alle Kassen gleiche Leistungen", "Aufnahmepflicht: Keine Kasse darf ablehnen (Grundversicherung!)", "Prämien variieren nach Kasse, Region und Modell"], speakText: "Seit 1996 muss jede Person in der Schweiz eine Grundversicherung haben. Es gibt freie Kassenwahl und einen einheitlichen Leistungskatalog. Keine Kasse darf in der Grundversicherung ablehnen." },
    { title: "Kostenbeteiligung", content: "Was der Versicherte selbst zahlt:", bulletPoints: ["Franchise: CHF 300 (Minimum) bis CHF 2'500 (Maximum) wählbar", "Kinder: CHF 0 bis CHF 600", "Selbstbehalt: 10% der Kosten über der Franchise", "Max. Selbstbehalt: CHF 700/Jahr (Erwachsene), CHF 350 (Kinder)", "Spitalbeitrag: CHF 15/Tag bei stationärem Aufenthalt", "Rechenbeispiel: Franchise 2'500 + max. SB 700 = max. CHF 3'200/Jahr"], speakText: "Die Franchise liegt zwischen 300 und 2'500 Franken. Dazu kommt ein Selbstbehalt von 10 Prozent, maximal 700 Franken pro Jahr. Die maximale Eigenleistung beträgt also 3'200 Franken." },
    { title: "Versicherungsmodelle", content: "Verschiedene Modelle mit unterschiedlichen Prämien:", bulletPoints: ["Standard (freie Arztwahl): Höchste Prämie", "Hausarztmodell: Erst zum Hausarzt, dann Überweisung", "HMO: Behandlung in HMO-Praxis, tiefste Prämie", "Telmed: Erst telefonisch beraten lassen", "Prämienersparnis: Bis 25% je nach Modell", "Achtung: Modellwechsel hat Kündigungsfristen!"], speakText: "Es gibt verschiedene Modelle: Standard mit freier Arztwahl, Hausarztmodell, HMO und Telmed. Alternative Modelle können bis zu 25 Prozent Prämie sparen." },
  ] } },
  { id: "kk1-2", title: "KVG Leistungen im Detail", type: "slides", duration: "30 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Was bezahlt die Grundversicherung?", content: "Gedeckte Leistungen:", bulletPoints: ["Arztbesuche und ambulante Behandlungen", "Stationäre Behandlung im Spital (allgemeine Abteilung)", "Medikamente auf der Spezialitätenliste", "Physiotherapie (auf Verordnung, max. 9 Sitzungen)", "Mutterschaftsleistungen (Kontrollen, Geburt, Nachbetreuung)", "Prävention: Impfungen, Vorsorgeuntersuchungen"], speakText: "Die Grundversicherung deckt Arztbesuche, Spitalaufenthalte in der allgemeinen Abteilung, Medikamente auf der Spezialitätenliste und Physiotherapie." },
    { title: "Was zahlt sie NICHT?", content: "Wichtige Ausschlüsse:", bulletPoints: ["Zahnbehandlungen (ausser unfallbedingt)", "Alternativmedizin über die gedeckten Methoden hinaus", "Halbprivat/Privat-Abteilung im Spital", "Auslandbehandlungen (nur Notfall, begrenzt)", "Brillen und Kontaktlinsen (nur für Kinder CHF 180/Jahr)", "Fitnessabos, Wellness, Schönheitsoperationen"], speakText: "Nicht gedeckt sind Zahnbehandlungen, Alternativmedizin, Halbprivat-Abteilung, Auslandbehandlungen und Brillen für Erwachsene." },
    { title: "Prämienverbilligung (IPV)", content: "Staatliche Unterstützung:", bulletPoints: ["Für Personen und Familien mit tiefem Einkommen", "Kantonal unterschiedlich geregelt", "Muss aktiv beantragt werden!", "Kinder: In vielen Kantonen automatisch vergünstigt", "Junge Erwachsene (18-25): Oft Sondertarife", "Tipp: Kunden auf IPV-Berechtigung hinweisen"], speakText: "Die Prämienverbilligung ist für Personen mit tiefem Einkommen. Sie ist kantonal geregelt und muss aktiv beantragt werden." },
  ] } },
  { id: "kk1-3", title: "Kassenwechsel beraten", type: "text", duration: "20 Min.", completed: false, content: { type: "text", paragraphs: [
    "Der Kassenwechsel ist eines der häufigsten Beratungsthemen. Hier das Wichtigste:",
    "Kündigungsfristen: Ordentliche Kündigung per 30. November für den 1. Januar (Standardfranchise). Bei Prämienerhöhung: Sonderkündigungsrecht. Die neue Kasse muss VOR der Kündigung bestätigt sein!",
    "Franchise-Wechsel: Höhere Franchise = tiefere Prämie. Rechne vor: Lohnt sich die höhere Franchise? Faustformel: Hohe Franchise nur wenn der Kunde selten zum Arzt geht und die Differenz spart.",
    "Modellwechsel: Von Standard zu Hausarzt/HMO/Telmed spart bis 25%. Aber: Einschränkung der Arztwahl! Prüfe ob der Hausarzt des Kunden im Netzwerk ist.",
    "Wichtig beim Wechsel: IMMER zuerst Zusatzversicherung bei der neuen Kasse beantragen! Wenn die Zusatzversicherung abgelehnt wird, kann der Kunde bei der alten Kasse bleiben. Grundversicherung kündigen erst NACH Zusatzversicherungs-Zusage!",
    "Dein Mehrwert: Du vergleichst alle Kassen für den Kunden. Du rechnest die Ersparnis konkret vor. Du kümmerst dich um den ganzen Wechselprozess. Das spart dem Kunden Zeit und Nerven.",
  ] } },
  { id: "kk1-4", title: "Quiz: KVG Grundlagen", type: "quiz", duration: "15 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
    { text: "Dürfen Krankenkassen Kunden in der Grundversicherung ablehnen?", options: ["Ja, bei Vorerkrankungen", "Nein, es gilt Aufnahmepflicht", "Nur über 65-Jährige", "Ja, bei hohem Risiko"], correctIndex: 1, explanation: "In der Grundversicherung gilt Aufnahmepflicht." },
    { text: "Wie hoch ist die maximale KVG-Franchise?", options: ["CHF 300", "CHF 1'500", "CHF 2'500", "CHF 5'000"], correctIndex: 2, explanation: "Maximum CHF 2'500 für Erwachsene." },
    { text: "Was ist der maximale Selbstbehalt pro Jahr?", options: ["CHF 350", "CHF 500", "CHF 700", "CHF 1'000"], correctIndex: 2, explanation: "Max. CHF 700/Jahr für Erwachsene, CHF 350 für Kinder." },
    { text: "Welches Modell hat die tiefsten Prämien?", options: ["Standard", "Hausarzt", "HMO", "Alle gleich"], correctIndex: 2, explanation: "HMO-Modelle haben typischerweise die tiefsten Prämien." },
    { text: "Was sollte man VOR der Kündigung der Grundversicherung tun?", options: ["Nichts", "Zusatzversicherung bei neuer Kasse beantragen", "Altes Abo kündigen", "Franchise erhöhen"], correctIndex: 1, explanation: "IMMER zuerst Zusatzversicherung bei der neuen Kasse beantragen!" },
    { text: "Bis wann muss man die Grundversicherung kündigen?", options: ["30. September", "30. Oktober", "30. November", "31. Dezember"], correctIndex: 2, explanation: "Ordentliche Kündigung per 30. November für den 1. Januar." },
  ] } },
] };
export default m;
