import type { Modul } from "../../lernpfade-data";
const m: Modul = { id: "kk2", title: "Zusatzversicherungen", description: "Spitalzusatz, Alternativmedizin, Zahnversicherung, Auslandschutz", credits: 35, lektionen: [
  { id: "kk2-1", title: "VVG vs. KVG", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Der entscheidende Unterschied", content: "Zusatzversicherungen unterliegen dem VVG:", bulletPoints: ["KVG (Grundversicherung): Aufnahmepflicht, einheitliche Leistungen", "VVG (Zusatzversicherung): Kasse DARF ablehnen!", "VVG: Gesundheitsprüfung vor Aufnahme", "VVG: Freie Prämiengestaltung (nach Alter, Geschlecht, Gesundheit)", "VVG: Unterschiedliche Leistungen je nach Kasse", "WICHTIG: Hier verdienst du als Vermittler!"], speakText: "Zusatzversicherungen unterliegen dem VVG, nicht dem KVG. Das bedeutet: Die Kasse darf ablehnen, macht Gesundheitsprüfungen und gestaltet Prämien und Leistungen frei." },
    { title: "Gesundheitsprüfung", content: "Worauf du achten musst:", bulletPoints: ["Der Kunde muss einen Gesundheitsfragebogen ausfüllen", "Wahrheitsgemässe Angaben sind Pflicht!", "Falsche Angaben: Versicherer kann Vertrag anfechten", "Vorerkrankungen können zu Vorbehalten oder Ablehnung führen", "Tipp: Antrag einreichen BEVOR der Kunde die alte Kasse kündigt", "Tipp: Bei mehreren Kassen gleichzeitig beantragen"], speakText: "Bei der Gesundheitsprüfung muss der Kunde wahrheitsgemässe Angaben machen. Reiche den Antrag ein bevor der Kunde die alte Kasse kündigt." },
  ] } },
  { id: "kk2-2", title: "Spitalzusatzversicherung", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Die drei Stufen", content: "Von Allgemein bis Privat:", bulletPoints: ["Allgemeine Abteilung: Gedeckt durch KVG (Mehrbettzimmer)", "Halbprivat: Zweibettzimmer, freie Arzt- und Spitalwahl Schweiz", "Privat: Einzelzimmer, Chefarztbehandlung, weltweite Deckung", "Flex-Modelle: Upgrade bei Bedarf (z.B. allgemein → halbprivat)", "Prämien steigen mit dem Alter stark!", "Früh abschliessen = günstiger und keine Vorerkrankungen"], speakText: "Die Spitalzusatzversicherung gibt es in drei Stufen: Halbprivat mit Zweibettzimmer, Privat mit Einzelzimmer und Chefarzt, und flexible Upgrade-Modelle." },
    { title: "Verkaufsargumente", content: "Warum der Kunde Spitalzusatz braucht:", bulletPoints: ["Freie Spitalwahl in der ganzen Schweiz (nicht nur Wohnkanton)", "Kürzere Wartezeiten bei Spezialisten", "Einzelzimmer: Ruhe und Privatsphäre bei Krankheit", "Chefarztbehandlung: Die besten Ärzte", "Rooming-in: Eltern können bei kranken Kindern übernachten", "Notfall im Ausland: Volle Deckung statt KVG-Minimum"], speakText: "Verkaufsargumente sind freie Spitalwahl, kürzere Wartezeiten, Einzelzimmer, Chefarztbehandlung und volle Auslanddeckung." },
  ] } },
  { id: "kk2-3", title: "Weitere Zusatzversicherungen", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Alternativmedizin", content: "Wachsender Markt:", bulletPoints: ["Akupunktur, Homöopathie, TCM, Osteopathie", "KVG deckt nur wenige anerkannte Methoden", "Zusatz: Breitere Abdeckung, höhere Limite", "Typisch: 80% Kostenübernahme, CHF 3'000-5'000/Jahr", "Viele Kunden nutzen regelmässig Alternativmedizin", "Gutes Verkaufsargument: Gesundheitsvorsorge"], speakText: "Alternativmedizin-Zusatzversicherungen decken Akupunktur, Homöopathie, TCM und Osteopathie. Typisch sind 80 Prozent Kostenübernahme bis 3'000 bis 5'000 Franken pro Jahr." },
    { title: "Zahnversicherung", content: "Oft unterschätzt:", bulletPoints: ["Zahnbehandlung ist im KVG NICHT gedeckt (ausser Unfall)", "Zahnversicherung: Für Kinder sehr empfehlenswert (Zahnspange!)", "Erwachsene: Prophylaxe, Füllungen, Kronen, Implantate", "Typisch: 50-75% Kostenübernahme, CHF 2'000-5'000/Jahr", "Wartefrist: Oft 6-12 Monate nach Abschluss", "Tipp: Für Kinder so früh wie möglich abschliessen"], speakText: "Zahnversicherung ist wichtig weil das KVG keine Zahnbehandlung deckt. Für Kinder besonders empfehlenswert wegen Zahnspangenkosten." },
    { title: "Auslandversicherung", content: "Für Reisende und Grenzgänger:", bulletPoints: ["KVG: Nur Notfall-Grundleistungen im Ausland", "Zusatz: Volle Behandlungskosten weltweit", "Rücktransport in die Schweiz", "Reiseannullierung und Gepäckverlust", "Für Vielreisende: Jahrespolice statt Einzelreiseversicherung", "Grenzgänger: Spezialregelungen beachten"], speakText: "Die Auslandversicherung deckt volle Behandlungskosten weltweit, Rücktransport und Reiseannullierung." },
  ] } },
  { id: "kk2-4", title: "Quiz: Zusatzversicherungen", type: "quiz", duration: "15 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
    { text: "Welchem Gesetz unterliegen Zusatzversicherungen?", options: ["KVG", "VVG", "OR", "ZGB"], correctIndex: 1, explanation: "Zusatzversicherungen unterliegen dem VVG (Versicherungsvertragsgesetz)." },
    { text: "Darf eine Kasse bei der Zusatzversicherung ablehnen?", options: ["Nein, Aufnahmepflicht", "Ja, nach Gesundheitsprüfung", "Nur über 60-Jährige", "Nie"], correctIndex: 1, explanation: "Ja, bei VVG-Produkten darf die Kasse nach Gesundheitsprüfung ablehnen." },
    { text: "Sind Zahnbehandlungen im KVG gedeckt?", options: ["Ja, immer", "Nur bei Unfall", "Nur für Kinder", "Ja, bis CHF 1'000"], correctIndex: 1, explanation: "Das KVG deckt Zahnbehandlungen nur wenn sie unfallbedingt sind." },
    { text: "Was bedeutet 'Halbprivat'?", options: ["Halbe Prämie", "Zweibettzimmer, freie Arzt- und Spitalwahl", "Nur für halbe Behandlungen", "50% Selbstbehalt"], correctIndex: 1, explanation: "Halbprivat = Zweibettzimmer mit freier Arzt- und Spitalwahl in der Schweiz." },
    { text: "Wann sollte man den Zusatzversicherungsantrag stellen?", options: ["Nach der Kündigung der alten Kasse", "VOR der Kündigung der alten Kasse", "Egal wann", "Nur am Jahresende"], correctIndex: 1, explanation: "IMMER VOR der Kündigung - falls der Antrag abgelehnt wird." },
  ] } },
] };
export default m;
