import type { Modul } from "../lernpfade-data";

const m1: Modul = {
  id: "m1-vw", title: "Versicherungswirtschaft Schweiz", description: "Geschichte, Marktüberblick, Akteure und Grundprinzipien", credits: 15,
  lektionen: [
    { id: "vw1", title: "Geschichte der Versicherung", type: "slides", duration: "15 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Ursprünge der Versicherung", content: "Die Idee der gegenseitigen Absicherung ist uralt. Von den Seefahrern im antiken Griechenland bis zu den Zünften im Mittelalter.", bulletPoints: ["Antikes Griechenland: Seedarlehen als erste Risikoabsicherung", "Mittelalter: Zünfte und Gilden als Solidargemeinschaften", "1347: Erste Seeversicherungspolice in Genua", "1666: Grosser Brand von London → Gründung erster Feuerversicherungen", "1778: Gründung der Helvetischen Brandassekuranz in Bern"], speakText: "Die Geschichte der Versicherung reicht Jahrtausende zurück. Schon im antiken Griechenland gab es Seedarlehen als erste Form der Risikoabsicherung. Im Mittelalter übernahmen Zünfte und Gilden die gegenseitige Absicherung ihrer Mitglieder. Die erste echte Versicherungspolice wurde 1347 in Genua ausgestellt. Nach dem Grossen Brand von London 1666 entstanden die ersten Feuerversicherungen. In der Schweiz wurde 1778 die Helvetische Brandassekuranz in Bern gegründet." },
      { title: "Schweizer Versicherungsgeschichte", content: "Die Schweiz hat eine reiche Versicherungstradition:", bulletPoints: ["1826: Gründung der Schweizerischen Mobiliar (ältester Privatversicherer)", "1857: Gründung der Helvetia in St. Gallen", "1872: Gründung der Zurich Insurance Group", "1875: Einführung der kantonalen Gebäudeversicherungen", "1948: Einführung der AHV (1. Säule)", "1985: BVG-Obligatorium (2. Säule)", "1996: KVG-Obligatorium (Krankenversicherung)"], speakText: "Die Schweiz hat eine reiche Versicherungstradition. Die Mobiliar wurde 1826 gegründet und ist der älteste Privatversicherer der Schweiz. 1948 wurde die AHV eingeführt, 1985 das BVG-Obligatorium und 1996 die obligatorische Krankenversicherung." },
    ] } },
    { id: "vw2", title: "Der Schweizer Versicherungsmarkt 2026", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Marktüberblick", content: "Der Schweizer Versicherungsmarkt ist einer der wichtigsten weltweit:", bulletPoints: ["Gesamtes Prämienvolumen: CHF 226.5 Mrd. (2024)", "Rund 195 Privatversicherer in 5 Versicherungszweigen", "Die Schweiz hat die höchste Versicherungsdichte weltweit (Prämien pro Kopf)", "Versicherungsbranche beschäftigt über 50'000 Personen", "Wichtigster Finanzplatz neben dem Bankensektor"], speakText: "Der Schweizer Versicherungsmarkt hat ein Gesamtprämienvolumen von 226.5 Milliarden Franken. Rund 195 Privatversicherer sind in 5 Versicherungszweigen tätig. Die Schweiz hat die höchste Versicherungsdichte weltweit und die Branche beschäftigt über 50'000 Personen." },
      { title: "Die grössten Versicherer", content: "Marktführer nach Bruttoprämienvolumen:", bulletPoints: ["1. Zurich Insurance Group: CHF 66.1 Mrd.", "2. Chubb: CHF 51.8 Mrd.", "3. Swiss Life: CHF 29.2 Mrd.", "4. AXA Schweiz: CHF 6.6 Mrd. (Prämienvolumen 2025: +7%)", "5. Mobiliar: CHF 4.8 Mrd.", "6. Helvetia: CHF 4.5 Mrd.", "7. Baloise: CHF 3.8 Mrd."], speakText: "Die grössten Schweizer Versicherer nach Prämienvolumen sind die Zurich Insurance Group mit 66.1 Milliarden, Chubb mit 51.8 Milliarden und Swiss Life mit 29.2 Milliarden Franken." },
      { title: "Aktuelle Trends 2025/2026", content: "Was den Markt aktuell bewegt:", bulletPoints: ["Cybervorfälle sind das Nr. 1 Risiko weltweit (10 Prozentpunkte Vorsprung)", "Digitale Transformation: Self-Service, Online-Schadenmeldung", "DigiSanté: Bund setzt auf Digitalisierung des Gesundheitswesens", "Klimawandel: Zunehmende Elementarschäden", "KI-Integration in Beratung und Schadenabwicklung", "Steigende Prämien für Organhaftpflichtversicherungen"], speakText: "Cybervorfälle sind das Nummer 1 Risiko weltweit. Die digitale Transformation treibt die Branche voran mit Self-Service und Online-Schadenmeldung. Der Klimawandel führt zu zunehmenden Elementarschäden und steigenden Prämien." },
    ] } },
    { id: "vw3", title: "Grundprinzipien der Versicherung", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Was ist Versicherung?", content: "Versicherung ist die Übertragung eines wirtschaftlichen Risikos auf einen Risikoträger gegen Bezahlung einer Prämie.", bulletPoints: ["Versicherungsnehmer (VN): Die versicherte Person/Firma", "Versicherer: Das Versicherungsunternehmen", "Prämie: Der Preis für den Versicherungsschutz", "Leistung: Die Zahlung im Schadenfall", "Police: Der Versicherungsvertrag"], speakText: "Versicherung ist die Übertragung eines wirtschaftlichen Risikos auf einen Risikoträger gegen Bezahlung einer Prämie. Die Grundelemente sind: der Versicherungsnehmer, der Versicherer, die Prämie, die Leistung im Schadenfall und die Police als Vertrag." },
      { title: "Das Gesetz der grossen Zahl", content: "Warum Versicherung funktioniert:", bulletPoints: ["Viele Versicherungsnehmer teilen das Risiko", "Der einzelne Schaden wird durch die Gemeinschaft getragen", "Je grösser die Gemeinschaft, desto genauer die Risikoberechnung", "Versicherungsmathematik (Aktuariat) berechnet die Wahrscheinlichkeiten", "Prämie = Schadenhäufigkeit × Schadenhöhe + Kosten + Gewinn"], speakText: "Versicherung funktioniert nach dem Gesetz der grossen Zahl. Viele Versicherungsnehmer teilen das Risiko. Der einzelne Schaden wird durch die Gemeinschaft getragen. Die Prämie ergibt sich aus Schadenhäufigkeit mal Schadenhöhe plus Kosten und Gewinn." },
      { title: "Versicherungsarten", content: "Drei Hauptkategorien:", bulletPoints: ["Personenversicherung: Leben, Kranken, Unfall, Erwerbsunfähigkeit", "Sachversicherung: Gebäude, Hausrat, Motorfahrzeug, Transport", "Haftpflichtversicherung: Privat-, Betriebs-, Berufshaftpflicht", "Weitere: Rechtsschutz, Reise, Cyber, Kredit"], speakText: "Es gibt drei Hauptkategorien von Versicherungen. Erstens Personenversicherungen wie Leben, Kranken und Unfall. Zweitens Sachversicherungen wie Gebäude, Hausrat und Motorfahrzeug. Drittens Haftpflichtversicherungen wie Privat- und Betriebshaftpflicht." },
      { title: "Obligatorische Versicherungen Schweiz", content: "Diese Versicherungen sind in der Schweiz Pflicht:", bulletPoints: ["KVG Grundversicherung (Krankenkasse)", "AHV/IV/EO (1. Säule)", "BVG (2. Säule, ab CHF 22'680 Jahreslohn)", "UVG (Unfallversicherung für Arbeitnehmende)", "Motorfahrzeug-Haftpflicht", "Gebäudeversicherung (in 19 Kantonen)", "Berufshaftpflicht (für bestimmte Berufe)"], speakText: "In der Schweiz sind folgende Versicherungen obligatorisch: Die KVG Grundversicherung, AHV, BVG ab einem Jahreslohn von 22'680 Franken, die UVG Unfallversicherung, die Motorfahrzeug-Haftpflicht und in 19 Kantonen die Gebäudeversicherung." },
    ] } },
    { id: "vw4", title: "Das Schweizer 3-Säulen-System", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Überblick 3-Säulen-System", content: "Das Schweizer Vorsorgesystem ist weltweit einzigartig:", bulletPoints: ["1. Säule: Staatliche Vorsorge (AHV/IV) → Existenzsicherung", "2. Säule: Berufliche Vorsorge (BVG/PK) → Lebensstandard", "3. Säule: Private Vorsorge (3a/3b) → Individuelle Ergänzung", "Ziel: 60-70% des letzten Einkommens im Alter"], speakText: "Das Schweizer 3-Säulen-System besteht aus der staatlichen Vorsorge als erste Säule für die Existenzsicherung, der beruflichen Vorsorge als zweite Säule zur Erhaltung des Lebensstandards, und der privaten Vorsorge als dritte Säule für individuelle Ergänzung." },
      { title: "1. Säule: AHV/IV/EO (2026)", content: "Aktuelle Zahlen der 1. Säule:", bulletPoints: ["Beitragssatz: 10.60% (je 5.30% AG/AN)", "Davon: AHV 4.35%, IV 0.70%, EO 0.25%", "Maximale AHV-Altersrente: CHF 2'450/Mt. (Einzelperson)", "Minimale AHV-Rente: CHF 1'225/Mt.", "NEU 2026: 13. AHV-Rente wird erstmals im Dezember ausbezahlt", "AHV-Referenzalter Frauen 2026: 64 Jahre 6 Monate (schrittweise bis 65)"], speakText: "Die erste Säule hat einen Beitragssatz von 10.60 Prozent, je hälftig Arbeitgeber und Arbeitnehmer. Die maximale AHV-Altersrente beträgt 2'450 Franken pro Monat. Neu 2026 wird erstmals die 13. AHV-Rente im Dezember ausbezahlt." },
      { title: "2. Säule: BVG (2026)", content: "Berufliche Vorsorge - aktuelle Kennzahlen:", bulletPoints: ["BVG-Obligatorium: CHF 22'680 bis CHF 90'720 Jahreslohn", "Koordinationsabzug: CHF 26'460", "Maximal versicherter Lohn: CHF 64'260", "Altersgutschriften: 7% (25-34J), 10% (35-44J), 15% (45-54J), 18% (55-65J)", "Arbeitgeber muss mind. 50% der Beiträge zahlen", "UVG-Höchstlohn: CHF 148'200"], speakText: "Die zweite Säule ist obligatorisch ab einem Jahreslohn von 22'680 Franken. Der Koordinationsabzug beträgt 26'460 Franken. Die Altersgutschriften steigen mit dem Alter von 7 Prozent bis 18 Prozent. Der Arbeitgeber muss mindestens 50 Prozent der Beiträge zahlen." },
      { title: "3. Säule: Private Vorsorge (2026)", content: "Steuerlich begünstigte Vorsorge:", bulletPoints: ["Säule 3a Maximum 2026: CHF 7'258 (mit PK)", "Säule 3a ohne PK: 20% des Nettoeinkommens, max. CHF 36'288", "Steuerersparnis in Zürich: ca. CHF 1'800-2'500 pro Jahr", "Säule 3b: Keine Limite, keine Steuerabzüge", "Bezug 3a: Frühestens 5 Jahre vor AHV-Alter", "Ausnahmen 3a: Eigenheim, Selbständigkeit, Auswanderung"], speakText: "Die Säule 3a erlaubt 2026 einen maximalen Beitrag von 7'258 Franken für Angestellte mit Pensionskasse. Ohne Pensionskasse sind es 20 Prozent des Nettoeinkommens. Die Steuerersparnis in Zürich beträgt etwa 1'800 bis 2'500 Franken pro Jahr." },
    ] } },
    { id: "vw5", title: "Quiz: Versicherungswirtschaft", type: "quiz", duration: "15 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
      { text: "Wie hoch ist das Gesamtprämienvolumen des Schweizer Versicherungsmarkts (2024)?", options: ["CHF 50 Mrd.", "CHF 120 Mrd.", "CHF 226.5 Mrd.", "CHF 500 Mrd."], correctIndex: 2, explanation: "Das Gesamtprämienvolumen beträgt CHF 226.5 Mrd. (2024)." },
      { text: "Wer ist der grösste Schweizer Versicherer nach Prämienvolumen?", options: ["AXA", "Mobiliar", "Swiss Life", "Zurich Insurance Group"], correctIndex: 3, explanation: "Die Zurich Insurance Group ist mit CHF 66.1 Mrd. der grösste." },
      { text: "Was ist das Nr. 1 Risiko weltweit laut aktuellen Studien?", options: ["Naturkatastrophen", "Cybervorfälle", "Pandemien", "Inflation"], correctIndex: 1, explanation: "Cybervorfälle führen die globale Risikotabelle mit 10 Prozentpunkten Vorsprung an." },
      { text: "Wie hoch ist der AHV-Beitragssatz 2026 (AG + AN)?", options: ["8.70%", "10.60%", "12.40%", "15.00%"], correctIndex: 1, explanation: "Der AHV/IV/EO-Beitragssatz beträgt 10.60%, je 5.30% für Arbeitgeber und Arbeitnehmer." },
      { text: "Was ist neu bei der AHV ab 2026?", options: ["Rentenalter 67", "13. AHV-Rente", "AHV-Abschaffung", "Halbierung der Renten"], correctIndex: 1, explanation: "Erstmals wird im Dezember 2026 die 13. AHV-Altersrente ausbezahlt." },
      { text: "Wie hoch ist der maximale Säule-3a-Beitrag 2026 (mit PK)?", options: ["CHF 5'000", "CHF 7'258", "CHF 10'000", "CHF 36'288"], correctIndex: 1, explanation: "Der Maximalbetrag für Erwerbstätige mit PK beträgt CHF 7'258." },
      { text: "Ab welchem Jahreslohn ist die BVG-Versicherung obligatorisch?", options: ["CHF 15'000", "CHF 22'680", "CHF 30'000", "CHF 50'000"], correctIndex: 1, explanation: "Das BVG-Obligatorium beginnt ab CHF 22'680 Jahreslohn." },
      { text: "Welches ist der älteste Privatversicherer der Schweiz?", options: ["Zurich", "Helvetia", "Mobiliar", "Baloise"], correctIndex: 2, explanation: "Die Schweizerische Mobiliar wurde 1826 gegründet." },
    ] } },
  ],
};

export default m1;
