import type { Modul } from "../lernpfade-data";

const m2: Modul = {
  id: "m2-recht", title: "Rechtskenntnisse & Regulierung", description: "VAG, FIDLEG, VVG, FINMA und Vermittlerpflichten", credits: 20,
  lektionen: [
    { id: "r1", title: "Das Versicherungsaufsichtsgesetz (VAG)", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
      { title: "VAG - Überblick", content: "Das revidierte VAG trat am 1. Januar 2024 in Kraft:", bulletPoints: ["Regelt die Aufsicht über Versicherungsunternehmen und Vermittler", "FINMA ist die zuständige Aufsichtsbehörde", "Ziel: Schutz der Versicherungsnehmer", "Neu: Strengere Anforderungen an Vermittler", "Typenzwang: Entweder gebunden ODER ungebunden"], speakText: "Das revidierte Versicherungsaufsichtsgesetz trat am 1. Januar 2024 in Kraft. Es regelt die Aufsicht über Versicherungsunternehmen und Vermittler. Neu gilt ein Typenzwang: Vermittler müssen sich für gebunden oder ungebunden entscheiden." },
      { title: "Gebundene vs. Ungebundene Vermittler", content: "Der wichtigste Unterschied:", bulletPoints: ["Gebunden: Treueverhältnis zum Versicherer, im VBV-Branchenregister", "Ungebunden: Treueverhältnis zum Kunden, im FINMA-Register", "Doppeltätigkeit ist VERBOTEN (Typenzwang)", "Gebundene: Versicherer haftet für den Vermittler", "Ungebundene: Eigene Berufshaftpflicht nötig, Entschädigungen offenlegen"], speakText: "Gebundene Vermittler stehen in einem Treueverhältnis zum Versicherer und sind im VBV-Branchenregister eingetragen. Ungebundene Vermittler stehen in einem Treueverhältnis zum Kunden und sind im FINMA-Register eingetragen. Eine Doppeltätigkeit ist verboten." },
    ] } },
    { id: "r2", title: "VBV-Registrierung und Zulassung 2026", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Neue Regelungen ab 2026", content: "Was sich ändert:", bulletPoints: ["Neues VBV-Branchenregister ersetzt CICERO (ab 01.01.2026)", "CICERO-Mitglieder werden automatisch überführt", "Wer nicht eingetragen ist → Zulassungsprüfung nötig", "Rezertifizierung alle 2 Jahre (NEU!)", "4 Prüfungsprofile: Allbranche, Leben, Nicht-Leben, Krankenzusatz"], speakText: "Ab 2026 ersetzt das neue VBV-Branchenregister das CICERO-Register. Bisherige CICERO-Mitglieder werden automatisch überführt. Neu wird alle 2 Jahre eine Rezertifizierung eingeführt. Es gibt 4 Prüfungsprofile: Allbranche, Leben, Nicht-Leben und Krankenzusatzversicherung." },
      { title: "VBV-Prüfungsstruktur", content: "So ist die Prüfung aufgebaut:", bulletPoints: ["1. Pflicht: 'Versicherungsgrundkenntnisse & Recht' (30 Min., CHF 400)", "2. Profil Nicht-Leben (60 Min., CHF 100)", "3. Profil Leben (60 Min., CHF 100)", "4. Profil Krankenzusatz (30 Min., CHF 100)", "Allbranche = alle Profile bestehen", "Prüfung: Online mit Proctoring, jederzeit verfügbar"], speakText: "Die VBV-Prüfung besteht aus einem Pflichtteil Versicherungsgrundkenntnisse und Recht, und dann den Profilen Nicht-Leben, Leben und Krankenzusatz. Wer alle bestehen will, erhält das Allbranche-Profil. Die Prüfungen finden online statt." },
    ] } },
    { id: "r3", title: "FIDLEG und Verhaltenspflichten", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
      { title: "FIDLEG - Was ist das?", content: "Das Finanzdienstleistungsgesetz:", bulletPoints: ["Regelt Verhaltenspflichten bei Finanzdienstleistungen", "Gilt auch für Versicherungsvermittler (über VAG umgesetzt)", "Ziel: Kundenschutz und Transparenz", "Informationspflichten vor Vertragsabschluss", "Dokumentationspflicht für jede Beratung"], speakText: "Das Finanzdienstleistungsgesetz regelt die Verhaltenspflichten bei Finanzdienstleistungen. Die FIDLEG-Pflichten gelten über das VAG auch für Versicherungsvermittler. Das Ziel ist Kundenschutz und Transparenz." },
      { title: "Pflichten im Detail", content: "Was du als Vermittler tun musst:", bulletPoints: ["Interessenkonflikte vermeiden oder offenlegen", "Basisinformationsblatt (BIB) bei qualifizierten LV abgeben", "Angemessenheitsprüfung durchführen", "Jede Beratung dokumentieren (Protokollpflicht!)", "Entschädigungen offenlegen (bei ungebundenen Vermittlern)", "Guter Ruf und fachliche Eignung nachweisen"], speakText: "Als Vermittler musst du Interessenkonflikte vermeiden oder offenlegen, ein Basisinformationsblatt bei qualifizierten Lebensversicherungen abgeben, eine Angemessenheitsprüfung durchführen und jede Beratung dokumentieren." },
    ] } },
    { id: "r4", title: "Das Versicherungsvertragsgesetz (VVG)", type: "text", duration: "15 Min.", completed: false, content: { type: "text", paragraphs: [
      "Das Versicherungsvertragsgesetz (VVG) regelt die Beziehung zwischen Versicherungsnehmer und Versicherer. Es ist das zentrale Gesetz für alle privaten Versicherungsverträge in der Schweiz.",
      "Wichtige Bestimmungen des VVG:",
      "Vorvertragliche Anzeigepflicht (Art. 4-8 VVG): Der Versicherungsnehmer muss alle Gefahrstatsachen wahrheitsgetreu angeben. Verletzt er diese Pflicht, kann der Versicherer vom Vertrag zurücktreten. Die Frist dafür beträgt 4 Wochen ab Kenntnis der Verletzung.",
      "Prämie und Vertragsdauer: Die Prämie ist zu Beginn jeder Versicherungsperiode fällig. Wird sie nicht rechtzelt bezahlt, kann der Versicherer eine Nachfrist von 14 Tagen setzen. Nach Ablauf ruht die Leistungspflicht.",
      "Schadenfall: Der Versicherungsnehmer muss den Schaden unverzüglich melden. Er muss die Schadenhöhe belegen und bei der Abklärung mitwirken. Absichtlich herbeigeführte Schäden sind nicht gedeckt.",
      "Überversicherung und Unterversicherung: Bei Überversicherung zahlt der Versicherer maximal den tatsächlichen Schaden. Bei Unterversicherung wird die Leistung proportional gekürzt (Proportionalitätsprinzip).",
      "Doppelversicherung: Ist die gleiche Sache bei mehreren Versicherern versichert, haften diese solidarisch. Der Versicherungsnehmer darf aber insgesamt nicht mehr als den Schaden erhalten.",
      "Verjährung: Ansprüche aus dem Versicherungsvertrag verjähren nach 2 Jahren (Sachversicherung) bzw. 5 Jahren (Personenversicherung) ab dem auslösenden Ereignis.",
    ] } },
    { id: "r5", title: "FINMA - Die Aufsichtsbehörde", type: "slides", duration: "15 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Aufgaben der FINMA", content: "Die eidgenössische Finanzmarktaufsicht:", bulletPoints: ["Beaufsichtigt Banken, Versicherer und Finanzmarktinfrastruktur", "Führt das Register der ungebundenen Vermittler", "Erteilt Bewilligungen und kann diese entziehen", "Kann Sanktionen aussprechen (Busse, Berufsverbot)", "Publiziert Rundschreiben und Aufsichtsmitteilungen"], speakText: "Die FINMA beaufsichtigt Banken, Versicherer und die Finanzmarktinfrastruktur. Sie führt das Register der ungebundenen Vermittler und kann Bewilligungen erteilen oder entziehen. Bei Verstössen kann sie Sanktionen wie Bussen oder Berufsverbote aussprechen." },
    ] } },
    { id: "r6", title: "Quiz: Recht & Regulierung", type: "quiz", duration: "15 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
      { text: "Wann trat das revidierte VAG in Kraft?", options: ["1. Januar 2022", "1. Januar 2024", "1. Januar 2025", "1. Januar 2026"], correctIndex: 1, explanation: "Das revidierte VAG trat am 1. Januar 2024 in Kraft." },
      { text: "Was bedeutet 'Typenzwang' bei Vermittlern?", options: ["Nur ein Versicherungstyp erlaubt", "Entweder gebunden ODER ungebunden", "Nur natürliche Personen", "Pflichtmitgliedschaft im VBV"], correctIndex: 1, explanation: "Typenzwang bedeutet, dass Vermittler entweder gebunden oder ungebunden tätig sein dürfen, nie beides gleichzeitig." },
      { text: "In welchem Register sind ungebundene Vermittler eingetragen?", options: ["VBV-Branchenregister", "CICERO", "FINMA-Register", "SVV-Register"], correctIndex: 2, explanation: "Ungebundene Vermittler müssen sich im FINMA-Vermittlerregister eintragen." },
      { text: "Wie oft muss man sich ab 2026 rezertifizieren?", options: ["Jedes Jahr", "Alle 2 Jahre", "Alle 5 Jahre", "Gar nicht"], correctIndex: 1, explanation: "Ab 2026 muss alle 2 Jahre eine Rezertifizierung erfolgen." },
      { text: "Was kostet die VBV-Pflichtprüfung 'Grundkenntnisse & Recht'?", options: ["CHF 100", "CHF 250", "CHF 400", "CHF 800"], correctIndex: 2, explanation: "Die Pflichtprüfung Versicherungsgrundkenntnisse & Recht kostet CHF 400." },
      { text: "Was muss bei qualifizierten Lebensversicherungen abgegeben werden?", options: ["Nur die Police", "Ein Basisinformationsblatt (BIB)", "Ein Gutachten", "Nichts"], correctIndex: 1, explanation: "Bei qualifizierten Lebensversicherungen muss ein Basisinformationsblatt (BIB) abgegeben werden." },
      { text: "Wie lang ist die Verjährungsfrist in der Sachversicherung?", options: ["1 Jahr", "2 Jahre", "5 Jahre", "10 Jahre"], correctIndex: 1, explanation: "In der Sachversicherung verjähren Ansprüche nach 2 Jahren." },
    ] } },
  ],
};

export default m2;
