import type { Modul } from "../lernpfade-data";

const m3: Modul = {
  id: "m3-sach", title: "Sach- und Vermögensversicherung", description: "Gebäude, Hausrat, Haftpflicht, Motorfahrzeug, Betrieb", credits: 30,
  lektionen: [
    { id: "s1", title: "Gebäudeversicherung Schweiz", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Kantonale Gebäudeversicherungen", content: "Das einzigartige System der Schweiz:", bulletPoints: ["19 Kantone: Obligatorische kantonale Gebäudeversicherung (Monopol)", "7 GUSTAVO-Kantone: Kein Monopol, private Versicherer", "GUSTAVO = Genf, Uri, Schwyz, Tessin, Appenzell Innerrhoden, Wallis, Obwalden", "In den Monopolkantonen: Kein Vermittlungsgeschäft möglich", "In GUSTAVO-Kantonen: Aktive Vermittlung möglich"], speakText: "19 Kantone haben eine obligatorische kantonale Gebäudeversicherung als Monopol. In den 7 GUSTAVO-Kantonen Genf, Uri, Schwyz, Tessin, Appenzell Innerrhoden, Wallis und Obwalden gibt es kein Monopol und private Versicherer bieten Gebäudeversicherungen an." },
      { title: "GUSTAVO-Kantone im Detail", content: "Unterschiede innerhalb der GUSTAVO-Kantone:", bulletPoints: ["Uri, Schwyz, Obwalden: Versicherung obligatorisch, aber bei Privatversicherern", "Genf, Tessin, AI, Wallis: Versicherung NICHT obligatorisch", "Ausnahme: Bezirk Oberegg (AI) hat eigene Gebäudeassekuranz", "Prämien in GUSTAVO oft höher als in Monopolkantonen", "Als Vermittler: Nur in GUSTAVO aktiv Gebäudeversicherungen vermittelbar"], speakText: "Innerhalb der GUSTAVO-Kantone gibt es Unterschiede. In Uri, Schwyz und Obwalden ist die Gebäudeversicherung obligatorisch, aber bei Privatversicherern abzuschliessen. In Genf, Tessin, Appenzell Innerrhoden und Wallis ist sie nicht obligatorisch." },
      { title: "Grunddeckung Gebäudeversicherung", content: "Was standardmässig gedeckt ist:", bulletPoints: ["Feuer: Brand, Blitzschlag, Explosion, Verpuffung", "Elementar: Hochwasser, Sturm (ab Windstärke 75 km/h), Hagel, Lawinen, Erdrutsch", "NICHT gedeckt: Erdbeben (meist Zusatzversicherung nötig)", "NICHT gedeckt: Krieg, Kernenergie, innere Unruhen", "Versicherungswert: Gebäudeversicherungswert oder Neuwert"], speakText: "Die Grunddeckung umfasst Feuer und Elementarschäden. Feuer bedeutet Brand, Blitzschlag und Explosion. Elementar bedeutet Hochwasser, Sturm ab Windstärke 75 Kilometer pro Stunde, Hagel, Lawinen und Erdrutsch. Erdbeben sind meist nicht in der Grunddeckung enthalten." },
    ] } },
    { id: "s2", title: "Versicherungswert und Unterversicherung", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Wertarten", content: "Die korrekte Wertermittlung ist fundamental:", bulletPoints: ["Neuwert: Kosten für Wiederherstellung in gleicher Art und Güte", "Zeitwert: Neuwert abzüglich Altersentwertung (Abschreibung)", "Verkehrswert (Marktwert): Preis bei Verkauf am Markt", "Amtlicher Wert: Steuerwert der Liegenschaft", "Gebäudeversicherungswert (GVW): Kantonaler Wert, oft vom Neuwert verschieden"], speakText: "Es gibt verschiedene Wertarten. Der Neuwert beschreibt die Kosten für eine Wiederherstellung. Der Zeitwert berücksichtigt die Altersentwertung. Der Verkehrswert ist der Marktpreis. Der amtliche Wert ist der Steuerwert." },
      { title: "Unterversicherung", content: "Eines der grössten Risiken für den Kunden:", bulletPoints: ["Definition: Versicherungssumme < tatsächlicher Wert", "Folge: Proportionale Kürzung der Leistung!", "Beispiel: Wert CHF 1'000'000, versichert CHF 500'000 = 50%", "Schaden CHF 200'000 → Versicherer zahlt nur CHF 100'000 (50%)", "Vermittlerpflicht: Kunden auf Unterversicherungsrisiko hinweisen!", "Lösung: Regelmässige Wertüberprüfung, Erste-Risiko-Deckung"], speakText: "Unterversicherung bedeutet, dass die Versicherungssumme tiefer ist als der tatsächliche Wert. Die Folge ist eine proportionale Kürzung der Leistung. Wenn ein Objekt im Wert von 1 Million nur mit 500'000 Franken versichert ist, zahlt der Versicherer bei einem Schaden von 200'000 Franken nur 100'000 Franken." },
    ] } },
    { id: "s3", title: "Hausratversicherung", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Was ist Hausrat?", content: "Definition und Umfang:", bulletPoints: ["Alle beweglichen Sachen im Haushalt", "Möbel, Kleider, Elektronik, Sportgeräte, Musikinstrumente", "Auch: Sachen von Gästen und Hausangestellten im Haushalt", "Wertsachen: Oft mit Sublimit (z.B. max. CHF 20'000 für Schmuck)", "NICHT: Motorfahrzeuge, Haustiere, Bargeld über Limite"], speakText: "Zum Hausrat gehören alle beweglichen Sachen im Haushalt. Das umfasst Möbel, Kleider, Elektronik, Sportgeräte und Musikinstrumente. Wertsachen wie Schmuck haben oft ein Sublimit." },
      { title: "Gedeckte Gefahren", content: "Standard-Deckung der Hausratversicherung:", bulletPoints: ["Feuer, Rauch, Explosion", "Einbruchdiebstahl (Einbruchspuren nötig!)", "Wasser: Leitungswasser, Rückstau", "Glasbruch (oft als Zusatz)", "Elementarschäden: Sturm, Hagel, Hochwasser", "Diebstahl auswärts: Oft als Zusatzdeckung", "Allgefahrendeckung (All Risk): Alles ausser explizit Ausgeschlossenes"], speakText: "Die Hausratversicherung deckt Feuer, Einbruchdiebstahl, Wasserschäden und Elementarschäden. Wichtig: Beim Einbruchdiebstahl müssen Einbruchspuren vorhanden sein. Eine Allgefahrendeckung deckt alles ausser explizit Ausgeschlossenes." },
    ] } },
    { id: "s4", title: "Privathaftpflichtversicherung", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Grundlagen Haftpflicht", content: "Wer einen Schaden verursacht, haftet:", bulletPoints: ["Verschuldenshaftung (Art. 41 OR): Wer schuldhaft einen Schaden verursacht", "Kausalhaftung: Haftung ohne Verschulden (z.B. Tierhalter, Fahrzeughalter)", "Geschäftsherrenhaftung (Art. 55 OR): Arbeitgeber haftet für Arbeitnehmer", "Werkeigentümerhaftung (Art. 58 OR): Eigentümer haftet für Mängel am Bauwerk"], speakText: "Es gibt verschiedene Haftungsarten. Die Verschuldenshaftung greift, wenn jemand schuldhaft einen Schaden verursacht. Die Kausalhaftung greift ohne Verschulden, zum Beispiel bei Tierhaltern. Die Geschäftsherrenhaftung macht den Arbeitgeber für Schäden seiner Arbeitnehmer haftbar." },
      { title: "Privathaftpflichtversicherung", content: "Schutz für Privatpersonen:", bulletPoints: ["Nicht obligatorisch, aber dringend empfohlen", "Deckungssumme: Typisch CHF 5-10 Mio.", "Deckt: Personenschäden, Sachschäden, Vermögensfolgeschäden", "Familie mitversichert (Ehepartner, Kinder)", "Wichtige Ausschlüsse: Vorsatz, Motorfahrzeuge (eigene MF-Versicherung)", "Weltweite Deckung (oft mit Einschränkungen für USA/Kanada)"], speakText: "Die Privathaftpflichtversicherung ist nicht obligatorisch aber dringend empfohlen. Die typische Deckungssumme beträgt 5 bis 10 Millionen Franken. Sie deckt Personen-, Sach- und Vermögensfolgeschäden. Die Familie ist mitversichert." },
    ] } },
    { id: "s5", title: "Motorfahrzeugversicherung", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Obligatorische MF-Haftpflicht", content: "Jedes zugelassene Fahrzeug braucht:", bulletPoints: ["MF-Haftpflicht ist obligatorisch (SVG Art. 63)", "Mindestdeckung: CHF 5 Mio. Personenschäden, CHF 1 Mio. Sachschäden", "Meistversicherer bieten CHF 100 Mio. Pauschaldeckung", "Deckt: Schäden die du ANDEREN verursachst", "Deckt NICHT: Schäden am eigenen Fahrzeug"], speakText: "Die Motorfahrzeug-Haftpflichtversicherung ist obligatorisch. Die Mindestdeckung beträgt 5 Millionen Franken für Personenschäden und 1 Million für Sachschäden. Sie deckt Schäden, die du anderen verursachst, nicht am eigenen Fahrzeug." },
      { title: "Kaskoversicherung", content: "Freiwilliger Schutz für das eigene Fahrzeug:", bulletPoints: ["Teilkasko: Feuer, Diebstahl, Glasbruch, Elementar, Kollision mit Tieren", "Vollkasko: Teilkasko + selbst verschuldete Kollisionsschäden", "Bonussystem: Prämienrabatt für schadenfreie Jahre (bis 70%)", "Bonusschutz: Erster Schaden ohne Bonusverlust (Zusatz)", "Parkschadendeckung: Fremdverschuldete Schäden im Stillstand", "Neupreisentschädigung: In den ersten 1-3 Jahren zum Neupreis"], speakText: "Die Teilkasko deckt Feuer, Diebstahl, Glasbruch und Elementarschäden. Die Vollkasko deckt zusätzlich selbst verschuldete Kollisionsschäden. Das Bonussystem bietet Rabatte für schadenfreie Jahre bis zu 70 Prozent." },
      { title: "Wichtige Zusatzdeckungen MF", content: "Was du deinen Kunden empfehlen solltest:", bulletPoints: ["Insassenunfallversicherung: Ergänzt UVG/KVG für Mitfahrer", "Pannenhilfe: Abschleppen, Mietfahrzeug, Weiterreise", "Grobfahrlässigkeit: Leistungskürzung bei Grobfahrlässigkeit vermeiden", "Auslandschutz (Carte Verte): Mindestschutz im Ausland", "E-Mobilität: Spezialdeckung für Akku, Ladestation, Ladekabel"], speakText: "Wichtige Zusatzdeckungen sind die Insassenunfallversicherung, Pannenhilfe, Grobfahrlässigkeitsdeckung und für Elektrofahrzeuge die E-Mobilitätsdeckung." },
    ] } },
    { id: "s6", title: "Betriebsversicherungen", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Betriebssachversicherung", content: "Schutz für Unternehmen:", bulletPoints: ["Gebäude, Einrichtung, Vorräte, Maschinen", "Betriebsunterbrechungsversicherung (BU): Ertragsausfall bei Stillstand", "BU-Deckung: Fixkosten + entgangener Gewinn", "Haftungszeit: Typisch 12-24 Monate", "Elektronikversicherung: IT-Infrastruktur, Server, Software"], speakText: "Die Betriebssachversicherung schützt Gebäude, Einrichtung, Vorräte und Maschinen eines Unternehmens. Die Betriebsunterbrechungsversicherung deckt den Ertragsausfall bei einem Stillstand, typischerweise für 12 bis 24 Monate." },
      { title: "Betriebshaftpflicht & Cyber", content: "Unverzichtbar für jedes Unternehmen:", bulletPoints: ["Betriebshaftpflicht: Schäden gegenüber Dritten durch Betriebstätigkeit", "Berufshaftpflicht: Für beratende Berufe (Vermögensschäden)", "Produkthaftpflicht: Schäden durch hergestellte/gelieferte Produkte", "Cyber-Versicherung: Schutz vor Hackerangriffen, Datenverlust", "Cyber: Nr. 1 Risiko weltweit → wachsender Markt!", "D&O (Directors & Officers): Organhaftpflicht für Geschäftsleitung"], speakText: "Die Betriebshaftpflicht deckt Schäden gegenüber Dritten. Die Cyber-Versicherung ist das am schnellsten wachsende Segment, da Cybervorfälle das Nummer 1 Risiko weltweit sind. Die D&O-Versicherung schützt die Geschäftsleitung." },
    ] } },
    { id: "s7", title: "Schadenabwicklung Praxis", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Der Schadenprozess", content: "Von der Meldung bis zur Auszahlung:", bulletPoints: ["1. Schadenmeldung: Sofort, mit Fotos und Dokumentation", "2. Schadenaufnahme: Versicherer prüft Deckung und Schadenhöhe", "3. Schadenexpertise: Bei grösseren Schäden unabhängiger Gutachter", "4. Regulierung: Berechnung der Entschädigung", "5. Auszahlung: Direkt an VN oder Werkstatt/Handwerker", "6. Regress: Versicherer fordert vom Verursacher zurück"], speakText: "Der Schadenprozess beginnt mit der sofortigen Schadenmeldung. Dann prüft der Versicherer die Deckung. Bei grösseren Schäden kommt ein Gutachter. Nach der Regulierung erfolgt die Auszahlung." },
      { title: "Deine Rolle als Vermittler", content: "So unterstützt du deinen Kunden:", bulletPoints: ["Hilf bei der Schadenmeldung (korrekt und vollständig)", "Dokumentation: Fotos, Rechnungen, Zeugenaussagen sammeln", "Vermittle zwischen Kunde und Versicherer", "Erkläre dem Kunden das Prozedere und die Fristen", "Nachbetreuung: Ist der Kunde zufrieden? Deckung anpassen?", "WICHTIG: Niemals zur Schadensübertreibung raten!"], speakText: "Als Vermittler unterstützt du den Kunden bei der Schadenmeldung, sammelst Dokumentation, vermittelst zwischen Kunde und Versicherer und stellst sicher, dass der Kunde zufrieden ist." },
    ] } },
    { id: "s8", title: "Quiz: Sachversicherung", type: "quiz", duration: "20 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
      { text: "Welche Kantone gehören NICHT zu den GUSTAVO-Kantonen?", options: ["Genf und Uri", "Zürich und Bern", "Schwyz und Tessin", "Wallis und Obwalden"], correctIndex: 1, explanation: "Zürich und Bern haben kantonale Gebäudeversicherungen (Monopol). GUSTAVO = GE, UR, SZ, TI, AI, VS, OW." },
      { text: "Was passiert bei Unterversicherung?", options: ["Versicherer zahlt trotzdem voll", "Proportionale Kürzung der Leistung", "Vertrag wird aufgelöst", "Prämie wird erhöht"], correctIndex: 1, explanation: "Bei Unterversicherung wird die Leistung proportional zur Unterversicherungsquote gekürzt." },
      { text: "Was ist bei Einbruchdiebstahl zwingend nötig für die Deckung?", options: ["Polizeibericht", "Einbruchspuren", "Videoaufnahme", "Zeugen"], correctIndex: 1, explanation: "Für die Deckung bei Einbruchdiebstahl müssen Einbruchspuren vorhanden sein." },
      { text: "Wie hoch ist die Mindestdeckung der MF-Haftpflicht für Personenschäden?", options: ["CHF 1 Mio.", "CHF 5 Mio.", "CHF 10 Mio.", "CHF 100 Mio."], correctIndex: 1, explanation: "Die gesetzliche Mindestdeckung für Personenschäden beträgt CHF 5 Mio." },
      { text: "Was deckt die Vollkasko ZUSÄTZLICH zur Teilkasko?", options: ["Diebstahl", "Glasbruch", "Selbst verschuldete Kollisionsschäden", "Elementarschäden"], correctIndex: 2, explanation: "Die Vollkasko deckt zusätzlich zur Teilkasko die selbst verschuldeten Kollisionsschäden." },
      { text: "Was ist eine Betriebsunterbrechungsversicherung?", options: ["Versicherung für Maschinenausfall", "Deckung für Ertragsausfall bei Betriebsstillstand", "Versicherung für Mitarbeiterunfälle", "Rechtsschutzversicherung"], correctIndex: 1, explanation: "Die BU-Versicherung deckt den Ertragsausfall (Fixkosten + entgangener Gewinn) bei Betriebsstillstand." },
      { text: "Welches ist das Nr. 1 Risiko weltweit?", options: ["Naturkatastrophen", "Cybervorfälle", "Terrorismus", "Inflation"], correctIndex: 1, explanation: "Cybervorfälle führen die globale Risikotabelle mit 10 Prozentpunkten Vorsprung an." },
      { text: "In welchen GUSTAVO-Kantonen ist die Gebäudeversicherung NICHT obligatorisch?", options: ["Uri, Schwyz, Obwalden", "Genf, Tessin, Appenzell Innerrhoden, Wallis", "Alle GUSTAVO-Kantone", "Keiner davon"], correctIndex: 1, explanation: "In Genf, Tessin, AI und Wallis ist die Gebäudeversicherung nicht obligatorisch." },
      { text: "Was deckt die Verschuldenshaftung (Art. 41 OR)?", options: ["Haftung ohne Verschulden", "Haftung bei schuldhafter Schadenverursachung", "Nur Sachschäden", "Nur Personenschäden"], correctIndex: 1, explanation: "Art. 41 OR regelt die Verschuldenshaftung: Wer schuldhaft einen Schaden verursacht, muss Schadenersatz leisten." },
    ] } },
  ],
};

export default m3;
