import type { Modul } from "../lernpfade-data";

const m4: Modul = {
  id: "m4-person", title: "Personen- und Sozialversicherung", description: "AHV, BVG, UVG, KVG, KTG, Lebensversicherung", credits: 35,
  lektionen: [
    { id: "p1", title: "Sozialversicherungen Überblick", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Das Schweizer Sozialversicherungssystem", content: "Eines der umfassendsten weltweit:", bulletPoints: ["AHV/IV/EO: Alters-, Hinterlassenen-, Invalidenversicherung (1. Säule)", "BVG: Berufliche Vorsorge / Pensionskasse (2. Säule)", "UVG: Obligatorische Unfallversicherung", "KVG: Obligatorische Krankenversicherung", "ALV: Arbeitslosenversicherung", "EO/MSE: Erwerbsersatzordnung, Mutterschaftsentschädigung", "FAK: Familienzulagen"], speakText: "Das Schweizer Sozialversicherungssystem umfasst die AHV als erste Säule, das BVG als zweite Säule, die obligatorische Unfallversicherung UVG, die obligatorische Krankenversicherung KVG, die Arbeitslosenversicherung ALV und die Familienzulagen." },
      { title: "Gesamtbelastung Sozialabgaben 2026", content: "Was Arbeitgeber und Arbeitnehmer zahlen:", bulletPoints: ["AHV/IV/EO: 10.60% (je 5.30%)", "ALV: 2.20% bis CHF 148'200 (je 1.10%)", "ALV Solidaritätsbeitrag: 0.50% auf Lohn > CHF 148'200", "BVG: Altersstaffel 7-18% (AG mind. 50%)", "UVG-BU: Durchschnitt 0.80% (nur AG)", "UVG-NBU: Durchschnitt 1.50% (nur AN)", "FAK: 1.0-3.0% kantonal (nur AG)", "Gesamtbelastung AG: ca. 13-19% des Bruttolohns"], speakText: "Die Gesamtbelastung für Sozialabgaben beträgt für den Arbeitgeber 13 bis 19 Prozent des Bruttolohns. Der grösste Posten ist die AHV mit 10.60 Prozent, gefolgt von der ALV mit 2.20 Prozent und dem BVG." },
    ] } },
    { id: "p2", title: "UVG - Unfallversicherung", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
      { title: "UVG Grundlagen", content: "Obligatorisch für alle Arbeitnehmenden:", bulletPoints: ["Berufsunfälle (BU): Prämie zahlt der Arbeitgeber", "Nichtberufsunfälle (NBU): Prämie zahlt der Arbeitnehmer", "NBU-Versicherung: Nur ab 8 Wochenstunden beim gleichen AG", "Unter 8h: Nichtberufsunfälle über KVG gedeckt", "Höchstversicherter Lohn 2026: CHF 148'200", "Selbständige: Können sich freiwillig versichern"], speakText: "Die UVG-Unfallversicherung ist obligatorisch für alle Arbeitnehmenden. Berufsunfälle werden vom Arbeitgeber bezahlt, Nichtberufsunfälle vom Arbeitnehmer. Die NBU-Versicherung gilt erst ab 8 Wochenstunden. Der Höchstlohn beträgt 148'200 Franken." },
      { title: "UVG Leistungen", content: "Was die Unfallversicherung zahlt:", bulletPoints: ["Heilungskosten: Arzt, Spital, Medikamente (keine Franchise!)", "Taggelder: 80% des versicherten Lohns ab 3. Tag", "Invalidenrente: Max. 80% des versicherten Lohns", "Hinterlassenenrente: Witwe 40%, Waisen 15% des versicherten Lohns", "Integritätsentschädigung: Einmalzahlung bei bleibenden Schäden", "Hilflosenentschädigung: Bei Pflegebedürftigkeit"], speakText: "Die UVG-Leistungen umfassen Heilungskosten ohne Franchise, Taggelder von 80 Prozent des versicherten Lohns ab dem dritten Tag, Invalidenrenten und Hinterlassenenrenten." },
      { title: "UVG vs. KVG - Der wichtige Unterschied", content: "Wann gilt was?", bulletPoints: ["UVG: Unfälle von Arbeitnehmenden (ab 8h/Woche)", "KVG: Krankheit + Unfälle von Nicht-Arbeitnehmenden", "KVG: Unfälle von Teilzeit < 8h/Woche", "UVG: KEINE Franchise, KEIN Selbstbehalt", "KVG: Franchise (CHF 300-2'500) + 10% Selbstbehalt", "Bei Unfall: Immer zuerst prüfen ob UVG greift!"], speakText: "Der wichtige Unterschied: Das UVG gilt für Unfälle von Arbeitnehmenden ab 8 Wochenstunden und hat keine Franchise. Das KVG gilt für Krankheiten und Unfälle von Nicht-Arbeitnehmenden und hat eine Franchise plus 10 Prozent Selbstbehalt." },
    ] } },
    { id: "p3", title: "KVG - Krankenversicherung", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Obligatorische Grundversicherung (OKP)", content: "Pflicht für alle Personen mit Wohnsitz in der Schweiz:", bulletPoints: ["Freie Wahl der Krankenkasse", "Einheitlicher Leistungskatalog (alle Kassen gleiche Leistungen)", "Aufnahmepflicht: Kassen dürfen niemanden ablehnen", "Franchise: CHF 300 (Minimum) bis CHF 2'500 (Maximum)", "Selbstbehalt: 10% der Kosten, max. CHF 700/Jahr", "Prämienverbilligung (IPV) für Personen mit tiefem Einkommen"], speakText: "Die obligatorische Grundversicherung gilt für alle Personen mit Wohnsitz in der Schweiz. Es gibt freie Kassenwahl und einen einheitlichen Leistungskatalog. Die Franchise liegt zwischen 300 und 2'500 Franken, dazu kommt ein Selbstbehalt von 10 Prozent." },
      { title: "Krankenzusatzversicherungen (VVG)", content: "Hier verdienst du als Vermittler:", bulletPoints: ["Unterliegen dem VVG (NICHT dem KVG) → freie Prämiengestaltung", "Kasse DARF ablehnen (Gesundheitsprüfung!)", "Spitalzusatz: Halbprivat, Privat, Einbett", "Alternativmedizin: Komplementärmedizin-Deckung", "Zahnversicherung: Prophylaxe und Behandlung", "Auslandschutz: Notfallbehandlung weltweit", "WICHTIG: Kunden sollten Zusatz VOR einem Kassenwechsel abschliessen!"], speakText: "Krankenzusatzversicherungen unterliegen dem VVG, nicht dem KVG. Das bedeutet freie Prämiengestaltung und die Kasse darf Kunden ablehnen. Angebote umfassen Spitalzusatz, Alternativmedizin, Zahnversicherung und Auslandschutz." },
    ] } },
    { id: "p4", title: "KTG - Krankentaggeldversicherung", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
      { title: "KTG Grundlagen", content: "Schutz bei Arbeitsunfähigkeit wegen Krankheit:", bulletPoints: ["KTG ist NICHT obligatorisch (aber in vielen GAV vorgeschrieben)", "Arbeitgeber muss bei Krankheit Lohn weiterzahlen (OR Art. 324a)", "Lohnfortzahlung: Abhängig von Dienstjahren (Berner/Basler/Zürcher Skala)", "1. Dienstjahr: 3 Wochen Lohnfortzahlung", "KTG-Versicherung: Ersetzt die Lohnfortzahlungspflicht", "Typische Deckung: 80% des Lohns, 720-730 Tage Leistungsdauer"], speakText: "Die Krankentaggeldversicherung schützt bei Arbeitsunfähigkeit wegen Krankheit. Sie ist nicht obligatorisch, aber in vielen Gesamtarbeitsverträgen vorgeschrieben. Ohne KTG muss der Arbeitgeber den Lohn weiterzahlen, abhängig von den Dienstjahren." },
      { title: "KTG für Arbeitgeber", content: "Warum jeder Arbeitgeber eine KTG braucht:", bulletPoints: ["Schützt den Arbeitgeber vor finanzieller Belastung", "Schützt den Arbeitnehmer bei langer Krankheit", "Wartefrist: Typisch 30, 60 oder 90 Tage", "Je kürzer die Wartefrist, desto höher die Prämie", "Prämie: Oft 50/50 zwischen AG und AN", "GAV-Konformität: Manche Branchen verlangen 720 Tage, 80%"], speakText: "Jeder Arbeitgeber sollte eine KTG-Versicherung haben. Sie schützt sowohl den Arbeitgeber vor finanzieller Belastung als auch den Arbeitnehmer bei langer Krankheit. Die Wartefrist beträgt typischerweise 30, 60 oder 90 Tage." },
    ] } },
    { id: "p5", title: "Lebensversicherung vertieft", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Arten der Lebensversicherung", content: "Die wichtigsten Produkte:", bulletPoints: ["Risikolebensversicherung: Reiner Todesfallschutz, tiefe Prämie", "Gemischte Lebensversicherung: Spar- + Risikokomponente", "Fondsgebundene LV: Anlage in Investmentfonds", "Reine Erlebensfallversicherung: Nur Auszahlung bei Erleben", "Freie Vorsorge 3b: Flexible Lebensversicherungspolice", "Gebundene Vorsorge 3a: Steuerbegünstigte Lebensversicherung"], speakText: "Die wichtigsten Lebensversicherungsarten sind die Risikolebensversicherung für reinen Todesfallschutz, die gemischte Lebensversicherung mit Spar- und Risikokomponente, und die fondsgebundene Lebensversicherung mit Anlage in Investmentfonds." },
      { title: "Rückkaufswert", content: "Das muss jeder Vermittler wissen:", bulletPoints: ["Rückkaufswert = Betrag bei vorzeitiger Kündigung", "In den ersten Jahren: Sehr tief oder CHF 0 (Abschlusskosten!)", "Nach 5 Jahren: Ca. 30-50% der eingezahlten Prämien", "Nach 10 Jahren: Ca. 70-85% der eingezahlten Prämien", "Kunden IMMER über tiefen Rückkaufswert in den ersten Jahren aufklären!", "Alternative: Prüfen ob Prämienbefreiung oder Umwandlung möglich"], speakText: "Der Rückkaufswert ist der Betrag bei vorzeitiger Kündigung. In den ersten Jahren ist er sehr tief wegen der Abschlusskosten. Nach 10 Jahren liegt er typischerweise bei 70 bis 85 Prozent der eingezahlten Prämien. Kunden müssen darüber aufgeklärt werden." },
      { title: "Säule 3a im Verkauf", content: "Das stärkste Verkaufsargument:", bulletPoints: ["Steuerersparnis sofort spürbar (CHF 1'800-2'500/Jahr in Zürich)", "Maximum 2026: CHF 7'258 (mit PK), CHF 36'288 (ohne PK)", "Bezug: Frühestens 5 Jahre vor AHV-Alter", "Ausnahmen: Eigenheim, Selbständigkeit, Auswanderung, IV-Rente", "Tipp: Mehrere 3a-Konten/Policen eröffnen (gestaffelte Auszahlung)", "Tipp: Früh beginnen → Zinseszinseffekt über Jahrzehnte"], speakText: "Die Säule 3a ist das stärkste Verkaufsargument. Die Steuerersparnis beträgt in Zürich 1'800 bis 2'500 Franken pro Jahr. Empfehle deinen Kunden, mehrere 3a-Konten zu eröffnen für eine gestaffelte Auszahlung." },
    ] } },
    { id: "p6", title: "Erwerbsunfähigkeit und Invalidität", type: "text", duration: "15 Min.", completed: false, content: { type: "text", paragraphs: [
      "Erwerbsunfähigkeit ist eines der grössten finanziellen Risiken. Als Vermittler musst du deine Kunden darauf aufmerksam machen und passende Lösungen anbieten.",
      "Die IV (Invalidenversicherung) als Teil der 1. Säule: Die IV-Rente beträgt bei Vollinvalidität maximal CHF 2'450/Monat (gleich wie AHV). Bei einem Invaliditätsgrad von mindestens 40% besteht Anspruch auf eine Teilrente. Die IV setzt stark auf 'Eingliederung vor Rente' und bietet Umschulungen und Arbeitsplatzanpassungen.",
      "Die BVG-Invalidenrente (2. Säule): Die BVG-Invalidenrente schliesst die Lücke zwischen IV und bisherigem Einkommen. Die Höhe hängt vom versicherten Lohn und den Altersgutschriften ab. Viele Pensionskassen bieten überobligatorische Leistungen.",
      "Private Erwerbsunfähigkeitsversicherung: Für Selbständige und Personen mit hohem Einkommen ist eine private EU-Versicherung wichtig. Sie schliesst die Lücke zwischen den Sozialversicherungsleistungen und dem tatsächlichen Einkommensverlust.",
      "Rechenbeispiel: Ein Angestellter verdient CHF 120'000/Jahr. Bei Vollinvalidität erhält er: IV-Rente ca. CHF 29'400/Jahr + BVG-Rente ca. CHF 25'000/Jahr = Total ca. CHF 54'400/Jahr. Das ist weniger als die Hälfte seines bisherigen Einkommens. Eine private EU-Versicherung kann diese Lücke von CHF 65'600 schliessen.",
      "Dein Beratungsauftrag: Zeige dem Kunden die konkrete Deckungslücke auf. Rechne vor, was bei Invalidität passiert. Biete massgeschneiderte Lösungen an. Das schafft Vertrauen und zeigt deinen Mehrwert als Berater.",
    ] } },
    { id: "p7", title: "Quiz: Personenversicherung", type: "quiz", duration: "20 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
      { text: "Ab wie vielen Wochenstunden beim gleichen AG ist man NBU-versichert?", options: ["4 Stunden", "8 Stunden", "12 Stunden", "20 Stunden"], correctIndex: 1, explanation: "Die NBU-Versicherung nach UVG gilt erst ab 8 Wochenstunden beim gleichen Arbeitgeber." },
      { text: "Was ist der Unterschied zwischen UVG und KVG bei den Kosten?", options: ["Kein Unterschied", "UVG hat keine Franchise, KVG schon", "KVG ist gratis", "UVG ist teurer"], correctIndex: 1, explanation: "Das UVG hat keine Franchise und keinen Selbstbehalt. Das KVG hat eine Franchise (CHF 300-2'500) plus 10% Selbstbehalt." },
      { text: "Was ist die maximale KVG-Franchise 2026?", options: ["CHF 300", "CHF 1'500", "CHF 2'500", "CHF 5'000"], correctIndex: 2, explanation: "Die maximale wählbare Franchise in der Grundversicherung beträgt CHF 2'500." },
      { text: "Wie hoch ist das UVG-Taggeld?", options: ["60% des Lohns", "70% des Lohns", "80% des Lohns", "100% des Lohns"], correctIndex: 2, explanation: "Das UVG-Taggeld beträgt 80% des versicherten Lohns ab dem 3. Tag." },
      { text: "Was ist der typische Rückkaufswert einer LV nach 10 Jahren?", options: ["10-20%", "30-50%", "70-85%", "100%"], correctIndex: 2, explanation: "Nach 10 Jahren liegt der Rückkaufswert typischerweise bei 70-85% der eingezahlten Prämien." },
      { text: "Dürfen Krankenkassen bei der Grundversicherung Kunden ablehnen?", options: ["Ja, bei Vorerkrankungen", "Nein, es gilt Aufnahmepflicht", "Nur über 65-Jährige", "Ja, bei hohem Risiko"], correctIndex: 1, explanation: "In der KVG-Grundversicherung gilt Aufnahmepflicht - keine Kasse darf einen Kunden ablehnen." },
      { text: "Wie hoch ist der maximale 3a-Beitrag 2026 ohne Pensionskasse?", options: ["CHF 7'258", "CHF 14'516", "CHF 36'288", "Unbegrenzt"], correctIndex: 2, explanation: "Ohne PK-Anschluss: 20% des Nettoeinkommens, maximal CHF 36'288." },
      { text: "Was deckt die KTG-Versicherung?", options: ["Unfallkosten", "Lohnausfall bei Krankheit", "Zahnbehandlung", "Spitalkosten"], correctIndex: 1, explanation: "Die KTG (Krankentaggeldversicherung) deckt den Lohnausfall bei Arbeitsunfähigkeit wegen Krankheit." },
    ] } },
  ],
};

export default m4;
