import type { Modul } from "../lernpfade-data";

const m5: Modul = {
  id: "m5-beratung", title: "Kundenberatung & Verkauf", description: "Gesprächsführung, Bedarfsanalyse, Abschluss, Ethik", credits: 20,
  lektionen: [
    { id: "b1", title: "Professionelle Gesprächsführung", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Struktur eines Beratungsgesprächs", content: "Jedes Gespräch folgt einem klaren Ablauf:", bulletPoints: ["1. Begrüssung und Smalltalk (2 Min.) → Vertrauen aufbauen", "2. Bedarfsanalyse (15 Min.) → Offene Fragen stellen", "3. Lösungspräsentation (10 Min.) → Nutzen statt Merkmale", "4. Einwandbehandlung (5 Min.) → Verständnis zeigen", "5. Abschluss (5 Min.) → Alternativfragen stellen", "6. Verabschiedung → Nächste Schritte vereinbaren"], speakText: "Jedes Beratungsgespräch folgt einem klaren Ablauf. Beginne mit der Begrüssung, dann die Bedarfsanalyse mit offenen Fragen, die Lösungspräsentation mit Fokus auf den Kundennutzen, die Einwandbehandlung und der Abschluss." },
      { title: "Aktives Zuhören", content: "Die wichtigste Fähigkeit eines Beraters:", bulletPoints: ["Paraphrasieren: 'Wenn ich Sie richtig verstehe...'", "Spiegeln: Emotionen des Kunden aufgreifen", "Nachfragen: 'Können Sie mir mehr dazu erzählen?'", "Zusammenfassen: 'Also zusammengefasst möchten Sie...'", "Schweigen: Dem Kunden Raum geben (3-Sekunden-Regel)"], speakText: "Aktives Zuhören ist die wichtigste Fähigkeit. Nutze Paraphrasieren, Spiegeln, Nachfragen, Zusammenfassen und bewusstes Schweigen." },
    ] } },
    { id: "b2", title: "Bedarfsanalyse meistern", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Die richtigen Fragen", content: "Offene Fragen bringen die besten Informationen:", bulletPoints: ["Familie: 'Wer lebt in Ihrem Haushalt?'", "Beruf: 'Was genau machen Sie beruflich?'", "Vermögen: 'Besitzen Sie Wohneigentum?'", "Vorsorge: 'Wie sieht Ihre aktuelle Vorsorgesituation aus?'", "Risiken: 'Worüber machen Sie sich Sorgen?'", "Budget: 'Was geben Sie aktuell für Versicherungen aus?'"], speakText: "Stelle offene Fragen zu Familie, Beruf, Vermögen, Vorsorge, Risiken und Budget. Diese Informationen brauchst du für eine fundierte Beratung." },
      { title: "Deckungslücken aufzeigen", content: "Der Schlüssel zum Verkauf:", bulletPoints: ["Vergleiche IST vs. SOLL Situation", "Rechne konkrete Zahlen vor (z.B. Invaliditätslücke)", "Nutze visuelle Hilfsmittel (Grafiken, Tabellen)", "Zeige Risiken auf, nicht Angst machen", "Priorisiere: Welche Lücke ist am dringendsten?"], speakText: "Zeige dem Kunden die Deckungslücken auf. Vergleiche die aktuelle Situation mit dem Bedarf. Rechne konkrete Zahlen vor, zum Beispiel die Einkommenslücke bei Invalidität." },
    ] } },
    { id: "b3", title: "Einwandbehandlung", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Die 5 häufigsten Einwände", content: "So reagierst du professionell:", bulletPoints: ["'Zu teuer' → 'Was genau finden Sie zu teuer? Darf ich aufzeigen was Sie dafür erhalten?'", "'Kein Bedarf' → 'Darf ich fragen: Was passiert wenn [Risiko eintritt]?'", "'Muss überlegen' → 'Was genau möchten Sie sich überlegen? Welche Fragen sind noch offen?'", "'Bin zufrieden' → 'Wann haben Sie zuletzt verglichen? Die Branche ändert sich schnell.'", "'Keine Zeit' → 'Wann passt es Ihnen besser? 15 Minuten genügen für einen Überblick.'"], speakText: "Bei Einwänden zeige immer Verständnis und stelle Rückfragen. Nie den Einwand ignorieren oder direkt widersprechen." },
      { title: "Die Bumerang-Technik", content: "Verwandle den Einwand in ein Argument:", bulletPoints: ["Kunde: 'Die Prämie ist zu hoch.'", "Du: 'Genau deshalb ist es so wichtig, die richtige Deckung zu haben. Lassen Sie mich zeigen, warum diese Lösung das beste Preis-Leistungsverhältnis bietet.'", "Prinzip: Einwand aufgreifen → umdrehen → als Vorteil präsentieren", "Übung: Schreibe für jeden der 5 Einwände eine Bumerang-Antwort"], speakText: "Die Bumerang-Technik verwandelt den Einwand in ein Verkaufsargument. Greife den Einwand auf, drehe ihn um und präsentiere ihn als Vorteil." },
    ] } },
    { id: "b4", title: "Compliance & Ethik in der Beratung", type: "text", duration: "15 Min.", completed: false, content: { type: "text", paragraphs: [
      "Als Versicherungsvermittler trägst du eine grosse Verantwortung. Du bist nicht nur Verkäufer, sondern Berater und Vertrauensperson für deine Kunden.",
      "Dokumentationspflicht: Seit dem revidierten VAG (2024) musst du jede Beratung dokumentieren. Halte fest: Welche Bedürfnisse hat der Kunde geäussert? Welche Produkte hast du empfohlen und warum? Welche Alternativen hast du aufgezeigt? Hat der Kunde die Risiken verstanden?",
      "Interessenkonflikte: Als ungebundener Vermittler stehst du in einem Treueverhältnis zum Kunden. Du musst seine Interessen über deine eigenen stellen. Alle Vergütungen müssen offengelegt werden. Empfiehl nie ein Produkt nur wegen der höheren Provision.",
      "Informationspflichten bei qualifizierten Lebensversicherungen: Du musst ein Basisinformationsblatt (BIB) abgeben und eine Angemessenheitsprüfung durchführen. Der Kunde muss verstehen, was er kauft.",
      "Best Practices: Stelle den Kunden immer in den Mittelpunkt. Empfiehl nur Produkte die du selbst verstehst. Erkläre komplexe Sachverhalte in einfacher Sprache. Sei ehrlich bei Einschränkungen und Ausschlüssen. Halte dich an alle regulatorischen Vorgaben. Bilde dich kontinuierlich weiter.",
      "Dein Ruf ist dein Kapital: In der Versicherungsbranche ist Vertrauen alles. Ein zufriedener Kunde bringt Empfehlungen. Ein unzufriedener Kunde kann deinen Ruf zerstören. Arbeite immer so, dass du morgen dem Kunden noch in die Augen schauen kannst.",
    ] } },
    { id: "b5", title: "Quiz: Beratungskompetenz", type: "quiz", duration: "15 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
      { text: "Was ist der erste Schritt in einem Beratungsgespräch?", options: ["Produkt präsentieren", "Vertrag unterschreiben", "Bedarfsanalyse", "Prämie berechnen"], correctIndex: 2, explanation: "Die Bedarfsanalyse steht immer am Anfang eines professionellen Beratungsgesprächs." },
      { text: "Was ist aktives Zuhören?", options: ["Einfach still sein", "Paraphrasieren, Spiegeln, Nachfragen", "Dem Kunden widersprechen", "Notizen machen"], correctIndex: 1, explanation: "Aktives Zuhören umfasst Paraphrasieren, Spiegeln, Nachfragen, Zusammenfassen und Schweigen." },
      { text: "Wie reagierst du auf 'Zu teuer'?", options: ["Preis sofort senken", "Fragen was genau zu teuer ist und Nutzen aufzeigen", "Gespräch beenden", "Anderes Produkt anbieten"], correctIndex: 1, explanation: "Frage nach, was genau zu teuer ist, und zeige den Nutzen und Wert der Lösung auf." },
      { text: "Was ist seit 2024 bei jeder Beratung Pflicht?", options: ["Kaffee anbieten", "Dokumentation des Gesprächs", "3 Offerten einholen", "Vertragsabschluss"], correctIndex: 1, explanation: "Seit dem revidierten VAG muss jede Beratung dokumentiert werden." },
      { text: "In welchem Verhältnis steht ein ungebundener Vermittler?", options: ["Treueverhältnis zum Versicherer", "Treueverhältnis zum Kunden", "Keinem Treueverhältnis", "Treueverhältnis zur FINMA"], correctIndex: 1, explanation: "Ungebundene Vermittler stehen in einem Treueverhältnis zum Kunden." },
    ] } },
  ],
};

export default m5;
