import type { Modul } from "../lernpfade-data";

const m6: Modul = {
  id: "m6-pruefung", title: "VBV Abschlussprüfung", description: "Prüfungsvorbereitung und Abschlussprüfung", credits: 30,
  lektionen: [
    { id: "pr1", title: "Prüfungsformat und Tipps", type: "text", duration: "15 Min.", completed: false, content: { type: "text", paragraphs: [
      "Die VBV-Zulassungsprüfung ab Juli 2026 hat ein neues Format. Hier erfährst du alles was du wissen musst.",
      "Prüfungsstruktur: Die Prüfung besteht aus 4 Profilen: 1. Versicherungsgrundkenntnisse & Versicherungsrecht (obligatorisch, 30 Min., CHF 400), 2. Nicht-Leben (60 Min., CHF 100), 3. Leben (60 Min., CHF 100), 4. Krankenzusatzversicherung (30 Min., CHF 100). Für die Allbranche musst du alle 4 Profile bestehen.",
      "Prüfungsform: Schriftliche Online-Prüfung mit Proctoring (Kameraüberwachung). Wissens- und Verständnisfragen (Multiple Choice). Die Prüfungen finden fortlaufend statt und können jederzeit über die VBV-Webseite gebucht werden.",
      "Rezertifizierung: Ab 2026 muss alle 2 Jahre eine Rezertifizierungsprüfung abgelegt werden. Das stellt sicher, dass dein Wissen aktuell bleibt.",
      "Prüfungstipps: Lerne in Etappen, nicht alles auf einmal. Nutze die Quizzes in der Academy zur Vorbereitung. Fokussiere auf Verständnis, nicht auf Auswendiglernen. Lies die Fragen genau durch, achte auf Wörter wie NICHT, IMMER, NIE. Bei Multiple Choice: Schliesse zuerst die offensichtlich falschen Antworten aus. Zeitmanagement: Teile die verfügbare Zeit gleichmässig auf alle Fragen auf.",
    ] } },
    { id: "pr2", title: "Zusammenfassung: Alle Module", type: "slides", duration: "30 Min.", completed: false, content: { type: "slides", slides: [
      { title: "Modul 1: Versicherungswirtschaft", content: "Die wichtigsten Fakten:", bulletPoints: ["Prämienvolumen Schweiz: CHF 226.5 Mrd.", "195 Privatversicherer in 5 Zweigen", "3-Säulen-System: AHV → BVG → 3a/3b", "AHV-Beitrag: 10.60%, NEU: 13. AHV-Rente 2026", "3a Maximum: CHF 7'258 (mit PK)", "BVG-Eintrittsschwelle: CHF 22'680"], speakText: "Im Modul Versicherungswirtschaft lerntest du den Schweizer Markt kennen. Das Prämienvolumen beträgt 226.5 Milliarden, es gibt 195 Privatversicherer und das 3-Säulen-System bildet die Grundlage der Vorsorge." },
      { title: "Modul 2: Recht & Regulierung", content: "Rechtliche Grundlagen:", bulletPoints: ["VAG: Versicherungsaufsichtsgesetz (revidiert 2024)", "VVG: Versicherungsvertragsgesetz", "FIDLEG: Finanzdienstleistungsgesetz (analog im VAG)", "Typenzwang: Gebunden ODER Ungebunden", "FINMA-Register (ungebunden) / VBV-Register (gebunden)", "Dokumentationspflicht bei jeder Beratung"], speakText: "Im Modul Recht lerntest du das VAG, VVG und die FIDLEG-Pflichten kennen. Wichtig ist der Typenzwang und die Dokumentationspflicht." },
      { title: "Modul 3: Sachversicherung", content: "Sach und Haftpflicht:", bulletPoints: ["GUSTAVO-Kantone: GE, UR, SZ, TI, AI, VS, OW", "Unterversicherung → proportionale Kürzung", "MF-Haftpflicht obligatorisch, Mindestdeckung CHF 5 Mio.", "Vollkasko = Teilkasko + selbstverschuldete Kollision", "Cyber = Nr. 1 Risiko weltweit", "Betriebsunterbrechung: Fixkosten + entgangener Gewinn"], speakText: "Im Modul Sachversicherung lerntest du die GUSTAVO-Kantone, Unterversicherung, Motorfahrzeug, Haftpflicht und Betriebsversicherungen kennen." },
      { title: "Modul 4: Personenversicherung", content: "Personen und Sozialversicherung:", bulletPoints: ["UVG: NBU ab 8h/Woche, kein Franchise, 80% Taggeld", "KVG: Aufnahmepflicht, Franchise CHF 300-2'500", "KTG: Lohnfortzahlung bei Krankheit (nicht obligatorisch)", "LV-Rückkaufswert: Nach 10 Jahren 70-85%", "EU-Lücke: Oft > 50% Einkommensverlust bei Invalidität", "UVG-Höchstlohn: CHF 148'200"], speakText: "Im Modul Personenversicherung lerntest du UVG, KVG, KTG, Lebensversicherung und Erwerbsunfähigkeit kennen." },
      { title: "Modul 5: Beratung", content: "Kundenberatung:", bulletPoints: ["Gesprächsstruktur: Begrüssung → Analyse → Lösung → Einwand → Abschluss", "Aktives Zuhören: Paraphrasieren, Spiegeln, Nachfragen", "Einwände: Verständnis zeigen, Bumerang-Technik", "Compliance: Dokumentationspflicht, Interessenkonflikte offenlegen", "Ungebundener Vermittler: Treueverhältnis zum Kunden"], speakText: "Im Modul Beratung lerntest du Gesprächsführung, Bedarfsanalyse, Einwandbehandlung und die ethischen Pflichten als Vermittler." },
    ] } },
    { id: "pr3", title: "Probequiz: Grundkenntnisse & Recht", type: "quiz", duration: "30 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
      { text: "Was ist der Typenzwang im neuen VAG?", options: ["Man muss alle Versicherungen vermitteln", "Man darf nur gebunden ODER ungebunden tätig sein", "Man muss bei der FINMA angestellt sein", "Man muss einen Hochschulabschluss haben"], correctIndex: 1, explanation: "Seit dem revidierten VAG gilt Typenzwang: Entweder gebunden oder ungebunden, nie beides." },
      { text: "Wie oft muss die VBV-Zertifizierung erneuert werden?", options: ["Jährlich", "Alle 2 Jahre", "Alle 5 Jahre", "Nie"], correctIndex: 1, explanation: "Ab 2026 ist alle 2 Jahre eine Rezertifizierungsprüfung nötig." },
      { text: "Was ist die Aufnahmepflicht im KVG?", options: ["Jeder muss sich versichern", "Krankenkassen dürfen niemanden ablehnen", "Arbeitgeber müssen zahlen", "Ärzte müssen behandeln"], correctIndex: 1, explanation: "In der Grundversicherung gilt Aufnahmepflicht: Keine Kasse darf einen Kunden ablehnen." },
      { text: "Ab welchem Alter steigen die BVG-Altersgutschriften auf 18%?", options: ["35 Jahre", "45 Jahre", "55 Jahre", "60 Jahre"], correctIndex: 2, explanation: "Ab 55 Jahren betragen die BVG-Altersgutschriften 18% des koordinierten Lohns." },
      { text: "Wie hoch ist die maximale AHV-Einzelrente?", options: ["CHF 1'225/Mt.", "CHF 2'450/Mt.", "CHF 3'675/Mt.", "CHF 5'000/Mt."], correctIndex: 1, explanation: "Die maximale AHV-Altersrente für Einzelpersonen beträgt CHF 2'450 pro Monat." },
      { text: "Was muss ein ungebundener Vermittler offenlegen?", options: ["Sein Gehalt", "Alle Arten von Entschädigungen", "Seine Kundenliste", "Seinen Ausbildungsstand"], correctIndex: 1, explanation: "Ungebundene Vermittler müssen alle Arten von Entschädigungen den Kunden offenlegen." },
      { text: "In welchen Kantonen ist die Gebäudeversicherung NICHT obligatorisch?", options: ["Zürich, Bern, Basel", "Genf, Tessin, AI, Wallis", "Uri, Schwyz, Obwalden", "Luzern, Zug, Schaffhausen"], correctIndex: 1, explanation: "In Genf, Tessin, Appenzell Innerrhoden und Wallis ist die Gebäudeversicherung nicht obligatorisch." },
      { text: "Was ist das Gesetz der grossen Zahl?", options: ["Je mehr Kunden, desto mehr Gewinn", "Je grösser die Gemeinschaft, desto genauer die Risikoberechnung", "Grosse Schäden sind wahrscheinlicher", "Nur grosse Versicherer überleben"], correctIndex: 1, explanation: "Das Gesetz der grossen Zahl besagt: Je mehr Versicherte, desto genauer die Schadenkalkulation." },
      { text: "Wie hoch ist das UVG-Taggeld?", options: ["60% des Lohns", "70% des Lohns", "80% des Lohns", "100% des Lohns"], correctIndex: 2, explanation: "Das UVG-Taggeld beträgt 80% des versicherten Verdienstes ab dem 3. Tag." },
      { text: "Was ist die 13. AHV-Rente?", options: ["Eine Rente für 13-Jährige", "Eine zusätzliche Monatsrente pro Jahr (neu ab 2026)", "Eine Sonderrente für Witwen", "Ein Zuschlag für Verheiratete"], correctIndex: 1, explanation: "Die 13. AHV-Rente ist eine zusätzliche Monatsrente, die erstmals im Dezember 2026 ausbezahlt wird." },
    ] } },
    { id: "pr4", title: "Probequiz: Allbranche", type: "quiz", duration: "45 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
      { text: "Was deckt die Teilkasko NICHT?", options: ["Diebstahl", "Glasbruch", "Selbstverschuldete Kollision", "Elementarschäden"], correctIndex: 2, explanation: "Selbstverschuldete Kollisionsschäden sind nur in der Vollkasko gedeckt." },
      { text: "Welches Dokument muss bei qualifizierten LV abgegeben werden?", options: ["Police", "Basisinformationsblatt (BIB)", "Steuererklärung", "Bankausweis"], correctIndex: 1, explanation: "Bei qualifizierten Lebensversicherungen muss ein Basisinformationsblatt abgegeben werden." },
      { text: "Was ist der Koordinationsabzug BVG 2026?", options: ["CHF 7'258", "CHF 22'680", "CHF 26'460", "CHF 90'720"], correctIndex: 2, explanation: "Der Koordinationsabzug beträgt CHF 26'460 (2026)." },
      { text: "Wann kann man Säule 3a frühestens beziehen?", options: ["Jederzeit", "5 Jahre vor AHV-Alter", "Bei Pensionierung", "Nach 20 Jahren"], correctIndex: 1, explanation: "Der 3a-Bezug ist frühestens 5 Jahre vor dem AHV-Referenzalter möglich." },
      { text: "Was ist eine Betriebsunterbrechungsversicherung?", options: ["Schutz für Maschinen", "Deckung für Ertragsausfall bei Stillstand", "Unfallversicherung für Mitarbeiter", "Haftpflicht für Kunden"], correctIndex: 1, explanation: "Die BU-Versicherung deckt Fixkosten und entgangenen Gewinn bei Betriebsstillstand." },
      { text: "Welche Versicherung hat KEINE Franchise?", options: ["KVG Grundversicherung", "UVG Unfallversicherung", "Hausratversicherung", "Rechtsschutzversicherung"], correctIndex: 1, explanation: "Die UVG-Unfallversicherung hat keine Franchise und keinen Selbstbehalt." },
      { text: "Was passiert bei der Bumerang-Technik?", options: ["Man gibt dem Kunden recht und geht", "Man dreht den Einwand in ein Verkaufsargument um", "Man ignoriert den Einwand", "Man senkt den Preis"], correctIndex: 1, explanation: "Die Bumerang-Technik verwandelt den Kundeneinwand in ein Verkaufsargument." },
      { text: "Wie hoch sind die BVG-Altersgutschriften für 35-44-Jährige?", options: ["7%", "10%", "15%", "18%"], correctIndex: 1, explanation: "Für 35 bis 44-Jährige betragen die BVG-Altersgutschriften 10% des koordinierten Lohns." },
      { text: "Wer muss sich im FINMA-Register eintragen?", options: ["Gebundene Vermittler", "Ungebundene Vermittler", "Alle Vermittler", "Nur Lebensversicherer"], correctIndex: 1, explanation: "Ungebundene Vermittler müssen sich im FINMA-Register eintragen, gebundene im VBV-Branchenregister." },
      { text: "Was ist der ALV-Solidaritätsbeitrag?", options: ["0.50% auf Lohn über CHF 148'200", "2.20% auf den Gesamtlohn", "1% Pauschale für alle", "Freiwilliger Beitrag"], correctIndex: 0, explanation: "Auf Lohnanteile über CHF 148'200 wird ein ALV-Solidaritätsbeitrag von 0.50% erhoben." },
      { text: "Was kostet die VBV-Grundkenntnisprüfung?", options: ["CHF 100", "CHF 200", "CHF 400", "CHF 600"], correctIndex: 2, explanation: "Die Prüfung Versicherungsgrundkenntnisse & Recht kostet CHF 400." },
      { text: "Wie viele Kantone haben eine obligatorische kantonale Gebäudeversicherung?", options: ["7", "13", "19", "26"], correctIndex: 2, explanation: "19 von 26 Kantonen haben eine obligatorische kantonale Gebäudeversicherung (Monopol)." },
    ] } },
  ],
};

export default m6;
