import type { Modul } from "../../lernpfade-data";
const m: Modul = { id: "t1", title: "Willkommen bei Zuriva", description: "Einführung, Werte, Kultur und dein Weg", credits: 15, lektionen: [
  { id: "t1-1", title: "Begrüssung von Mark", type: "video", duration: "5 Min.", completed: false, content: { type: "video", description: "Mark heisst dich willkommen und erklärt dir die 4 Zuriva-Werte: Kundenorientierung, Qualität, Vertrauen und Innovation. Er erklärt auch, dass Zuriva ein ungebundener Vermittler ist - das heisst: unabhängig von Versicherern und nur dem Kunden verpflichtet. Zuriva arbeitet mit über 8 Schweizer Versicherungspartnern zusammen.", speakText: "Hallo! Ich bin Mark, dein persönlicher Begleiter bei Zuriva. Schön, dass du da bist. Die Zuriva Academy wurde für dich gebaut. Wir stehen für 4 Werte: Erstens Kundenorientierung. Der Kunde steht immer im Mittelpunkt. Zweitens Qualität. Wir beraten fundiert und umfassend. Drittens Vertrauen. Ehrlichkeit und Transparenz in jeder Beratung. Und viertens Innovation. Wir nutzen modernste Technologie. Als ungebundener Vermittler sind wir unabhängig. Wir arbeiten mit über 8 Schweizer Versicherungspartnern zusammen und wählen immer die beste Lösung für den Kunden. Ich wünsche dir viel Erfolg!", image: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&q=80" } },
  { id: "t1-2", title: "Deine 5 Lernpfade", type: "slides", duration: "15 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Dein Weg zur VBV-Zertifizierung", content: "Die Academy hat 5 Lernpfade mit insgesamt über 110 Stunden Lernstoff. Du arbeitest sie der Reihe nach durch.", bulletPoints: ["1. Trainee Grundausbildung (20h) – Du bist hier!", "2. VBV Grundausbildung (30h) – Pflichtausbildung für die Zertifizierung", "3. VBV Krankenkassenzusatz (20h) – Spezialisierung Krankenversicherung", "4. VBV Sach- und Vermögen (20h) – Spezialisierung Nicht-Leben", "5. VBV Mündliche Prüfung (20h) – Prüfungsvorbereitung"], speakText: "Die Academy hat 5 Lernpfade. Du startest mit der Trainee Grundausbildung und arbeitest dich bis zur VBV-Prüfung hoch. Insgesamt sind es über 110 Stunden Lernstoff.", image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1200&q=80" },
    { title: "Die VBV-Prüfung 2026", content: "Seit 2026 muss jeder Versicherungsvermittler eine VBV-Prüfung bestehen. Ohne bestandene Prüfung: Kein Registereintrag, kein Vermitteln.", bulletPoints: ["Generelle Fähigkeiten & Kenntnisse: 30 Min., CHF 400 (Pflicht!)", "Nicht-Leben: 60 Min., CHF 100", "Leben: 60 Min., CHF 100", "Krankenzusatz: 30 Min., CHF 100", "Mündliche Prüfung: 30 Min., CHF 200 (vor Ort in Bern)", "Rezertifizierung: Alle 2 Jahre"], speakText: "Die VBV-Prüfung hat 4 schriftliche Teile und einen mündlichen Teil. Die Generelle Prüfung kostet 400 Franken und dauert 30 Minuten. Der mündliche Teil findet in Bern statt und dauert ebenfalls 30 Minuten.", image: "https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=1200&q=80" },
  ] } },
  { id: "t1-3", title: "Quiz: Willkommen", type: "quiz", duration: "5 Min.", completed: false, content: { type: "quiz", passingScore: 60, questions: [
    { text: "Was bedeutet 'ungebundener Vermittler'?", options: ["Bei einer Versicherung angestellt", "Unabhängig, dem Kunden verpflichtet", "Ohne Ausbildung", "Nur online beratend"], correctIndex: 1, explanation: "Mark hat erklärt: Ungebunden heisst unabhängig und dem Kunden verpflichtet." },
    { text: "Wie viele Versicherungspartner hat Zuriva?", options: ["3", "5", "Über 8", "Über 20"], correctIndex: 2, explanation: "Mark hat gesagt: Zuriva arbeitet mit über 8 Schweizer Partnern zusammen." },
    { text: "Wie viele Lernpfade hat die Academy?", options: ["3", "4", "5", "7"], correctIndex: 2, explanation: "In der Lektion 'Deine 5 Lernpfade' hast du gelernt: Es gibt 5 Lernpfade." },
    { text: "Wie viel kostet die VBV-Grundprüfung?", options: ["CHF 100", "CHF 200", "CHF 400", "CHF 600"], correctIndex: 2, explanation: "Generelle Fähigkeiten & Kenntnisse: CHF 400." },
    { text: "Wo findet die mündliche VBV-Prüfung statt?", options: ["Online", "Zürich", "Bern", "Basel"], correctIndex: 2, explanation: "Die mündliche Prüfung findet vor Ort in Bern statt." },
    { text: "Wie oft muss die VBV-Zertifizierung erneuert werden?", options: ["Jährlich", "Alle 2 Jahre", "Alle 5 Jahre", "Nie"], correctIndex: 1, explanation: "Rezertifizierung ist alle 2 Jahre nötig." },
  ] } },
] };
export default m;
