import type { Modul } from "../../lernpfade-data";
const m: Modul = { id: "t1", title: "Willkommen bei Zuriva", description: "Einführung, Werte, Kultur und dein Weg", credits: 15, lektionen: [
  { id: "t1-1", title: "Begrüssung von Mark", type: "video", duration: "5 Min.", completed: false, content: { type: "video", description: "Mark heisst dich persönlich willkommen in der Zuriva Academy. Er erklärt dir, was dich erwartet und wie du das Beste aus deiner Ausbildung machst.", speakText: "Hallo! Ich bin Mark, dein persönlicher Begleiter bei Zuriva. Schön, dass du da bist. Du bist jetzt Teil von etwas Besonderem. Die Zuriva Academy wurde für dich gebaut. Hier lernst du alles, was du als Versicherungsprofi brauchst. Schritt für Schritt. In deinem Tempo. Wir stehen für drei Dinge. Qualität. Vertrauen. Und Innovation. Dich erwarten spannende Kurse, interaktive Prüfungen und echte Zertifikate für deine Karriere. Das Beste daran? Du bist nie allein. Ich bin immer für dich da. Bei jeder Lektion. Bei jeder Frage. Gemeinsam machen wir dich fit für die VBV Zertifizierung 2026. Also, bist du bereit? Dann lass uns loslegen!", image: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&q=80" } },
  { id: "t1-2", title: "Die Zuriva Werte", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Unsere Mission", content: "Zuriva steht für erstklassige, unabhängige Versicherungsberatung in der Schweiz. Wir beraten ehrlich, transparent und immer im Interesse des Kunden.", bulletPoints: ["Kundenorientierung: Der Kunde steht immer im Mittelpunkt jeder Entscheidung", "Qualität: Wir beraten fundiert, umfassend und auf dem neuesten Stand", "Vertrauen: Ehrlichkeit und Transparenz in jeder einzelnen Beratung", "Innovation: Wir nutzen modernste Technologie für bessere Ergebnisse", "Unabhängigkeit: Als ungebundener Vermittler sind wir nur dem Kunden verpflichtet"], speakText: "Zuriva steht für erstklassige Versicherungsberatung. Unsere fünf Werte sind Kundenorientierung, Qualität, Vertrauen, Innovation und Unabhängigkeit. Als ungebundener Vermittler sind wir nur dem Kunden verpflichtet.", image: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1200&q=80" },
    { title: "Ungebundene Vermittlung", content: "Als ungebundener Versicherungsvermittler bist du unabhängig von einzelnen Versicherungsgesellschaften. Das ist dein grösster Vorteil gegenüber gebundenen Vermittlern.", bulletPoints: ["Wir arbeiten mit über 8 führenden Schweizer Versicherungspartnern", "Du bist dem Kunden verpflichtet, nicht einem Versicherer", "Freie Produktwahl: Immer die objektiv beste Lösung für den Kunden", "Transparenz: Alle Vergütungen und Provisionen werden offengelegt", "Kein Verkaufsdruck: Du empfiehlst was der Kunde wirklich braucht", "Vergleichsofferten: Mehrere Anbieter nebeneinander für den Kunden"], speakText: "Als ungebundener Vermittler arbeitest du mit über 8 Partnern zusammen. Du bist dem Kunden verpflichtet und wählst immer die beste Lösung. Alle Vergütungen werden offengelegt.", image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1200&q=80" },
    { title: "Unsere Partner", content: "Mit diesen führenden Schweizer Versicherern arbeiten wir zusammen:", bulletPoints: ["Helvetia: Stark in Sach-, Haftpflicht- und Motorfahrzeugversicherung", "Zurich Insurance: Umfassendes Portfolio inkl. Cyber-Versicherung", "Swiss Life: Marktführer in Lebensversicherung und Vorsorge", "AXA: Grösster Allbranchenversicherer der Schweiz (CHF 6.6 Mrd.)", "Mobiliar: Ältester Privatversicherer, stark im Schadengeschäft", "CSS: Spezialist für Krankenversicherung", "Baloise: Traditionsreich, stark bei Privat- und KMU-Kunden", "Allianz: International, Leben und Vorsorge"], speakText: "Wir arbeiten mit Helvetia, Zurich, Swiss Life, AXA, Mobiliar, CSS, Baloise und Allianz zusammen. Für jeden Kundenbedarf der passende Partner.", image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80" },
  ] } },
  { id: "t1-3", title: "So funktioniert die Academy", type: "slides", duration: "15 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Dein Lernweg: 5 Lernpfade", content: "Die Academy ist strukturiert aufgebaut. Du arbeitest dich Schritt für Schritt durch 5 Lernpfade:", bulletPoints: ["1. Trainee Grundausbildung (20h) – Du bist hier! Der perfekte Einstieg.", "2. VBV Grundausbildung (30h) – Pflichtausbildung für die Zertifizierung", "3. VBV Krankenkassenzusatz (20h) – Spezialisierung Krankenversicherung", "4. VBV Sach- und Vermögen (20h) – Spezialisierung Nicht-Leben", "5. VBV Mündliche Prüfung (20h) – Vorbereitung auf die mündliche Prüfung", "Total: Über 110 Stunden Lernstoff, der dich zum Experten macht"], speakText: "Die Academy hat 5 Lernpfade mit über 110 Stunden Lernstoff. Du startest mit der Trainee Grundausbildung und arbeitest dich bis zur VBV-Prüfung hoch.", image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1200&q=80" },
    { title: "Lektionsarten", content: "Du lernst auf verschiedene Arten - für maximalen Lernerfolg:", bulletPoints: ["Videos: Mark erklärt dir die Themen persönlich mit echter Stimme", "Slides: Interaktive Folien mit Bildern, Bullet Points und Vorlesen-Funktion", "Texte: Vertiefende Informationen zum selbständigen Lesen", "Quizzes: Teste dein Wissen nach jedem Modul mit sofortigem Feedback", "Kahoot: Spielerische Wissenstests im Wettbewerb", "Am Ende jedes Lernpfads: Eine VBV-Prüfungssimulation"], speakText: "Du lernst durch Videos, interaktive Slides, Texte und Quizzes. Am Ende jedes Lernpfads wartet eine Prüfungssimulation.", image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1200&q=80" },
    { title: "Gamification & Motivation", content: "Lernen soll Spass machen! Deshalb gibt es:", bulletPoints: ["XP-Punkte: Sammle Erfahrungspunkte für jede abgeschlossene Lektion", "Level-System: Steige auf und schalte neue Inhalte frei", "Badges: Verdiene Abzeichen für besondere Leistungen", "Streak: Halte deine Lernserie aufrecht für Bonus-XP", "Leaderboard: Vergleiche dich mit deinen Kolleginnen und Kollegen", "Zertifikate: Offizielle Nachweise für abgeschlossene Lernpfade"], speakText: "Lernen macht bei uns Spass. Sammle XP, steige im Level auf, verdiene Badges und halte deinen Streak aufrecht. Am Ende warten offizielle Zertifikate.", image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&q=80" },
  ] } },
  { id: "t1-4", title: "Deine VBV-Zertifizierung 2026", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Warum VBV-Zertifizierung?", content: "Seit dem 1. Januar 2026 gelten neue Regeln für alle Versicherungsvermittler in der Schweiz.", bulletPoints: ["Jeder Vermittler muss eine VBV-Zulassungsprüfung bestehen", "Ohne Zertifizierung: Kein Eintrag ins Register = kein Vermitteln!", "Das revidierte VAG (Versicherungsaufsichtsgesetz) schreibt dies vor", "Ziel: Besserer Kundenschutz durch qualifizierte Berater", "Die FINMA und der VBV überwachen die Einhaltung", "Die Zuriva Academy bereitet dich optimal auf alle Prüfungen vor"], speakText: "Seit 2026 muss jeder Versicherungsvermittler eine VBV-Zulassungsprüfung bestehen. Ohne Zertifizierung darfst du nicht vermitteln. Die Zuriva Academy bereitet dich optimal vor.", image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&q=80" },
    { title: "Die Prüfungsstruktur", content: "Die VBV-Prüfung besteht aus 4 schriftlichen Teilen + 1 mündlichen Teil:", bulletPoints: ["1. Generelle Fähigkeiten & Kenntnisse: 30 Min., CHF 400 (Pflicht!)", "2. Nicht-Leben: 60 Min., CHF 100 (Sach- und Vermögensversicherung)", "3. Leben: 60 Min., CHF 100 (Lebens- und Personenversicherung)", "4. Krankenzusatzversicherung: 30 Min., CHF 100", "5. Mündliche Prüfung: 30 Min., CHF 200 (vor Ort in Bern)", "Für die Allbranche: Alle 5 Teile bestehen!"], speakText: "Die Prüfung hat 4 schriftliche Teile online und einen mündlichen Teil in Bern. Für die Allbranche musst du alle 5 bestehen.", image: "https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=1200&q=80" },
    { title: "Prüfungsformat", content: "So laufen die schriftlichen Prüfungen ab:", bulletPoints: ["Online-Fernprüfung mit Proctoring (Kameraüberwachung)", "Wissens- und Verständnisfragen (Multiple Choice)", "Geleitete Fallbearbeitung (praktische Szenarien)", "Prüfungen finden fortlaufend statt - jederzeit buchbar über vbv.ch", "Ergebnis: Sofort nach der Prüfung", "Bei Nichtbestehen: Wiederholung möglich"], speakText: "Die schriftlichen Prüfungen sind Online-Fernprüfungen mit Kameraüberwachung. Sie bestehen aus Multiple Choice und Fallbearbeitungen. Du kannst sie jederzeit über die VBV-Webseite buchen.", image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&q=80" },
    { title: "Rezertifizierung", content: "Die Zertifizierung ist nicht für immer - du musst sie auffrischen:", bulletPoints: ["Alle 2 Jahre: Rezertifizierungsprüfung (ab 2026)", "Jährliche Gebühr: CHF 100 für Prüfung und Dossierführung", "Ziel: Sicherstellen dass dein Wissen aktuell bleibt", "Die Zuriva Academy hält deine Inhalte immer auf dem neuesten Stand", "Compliance-Updates werden automatisch in die Academy integriert", "Tipp: Regelmässig lernen statt kurz vor der Rezertifizierung pauken"], speakText: "Alle 2 Jahre musst du eine Rezertifizierungsprüfung ablegen. Das kostet 100 Franken pro Jahr. Die Zuriva Academy hält deine Inhalte aktuell.", image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&q=80" },
  ] } },
  { id: "t1-5", title: "Dein erster Tag", type: "text", duration: "15 Min.", completed: false, content: { type: "text", paragraphs: [
    "Herzlich willkommen zu deinem ersten Tag als Zuriva-Trainee! Hier erfährst du, was dich in den nächsten Wochen erwartet und wie du dich am besten vorbereitest.",
    "Dein Tagesablauf: Als Trainee wirst du morgens mit Lerneinheiten in der Academy starten. Plane täglich 1-2 Stunden für die Academy ein. Nachmittags begleitest du erfahrene Berater bei Kundenterminen. So verbindest du Theorie und Praxis optimal.",
    "Deine Ausrüstung: Du erhältst einen Laptop mit allen nötigen Tools - CRM-System, Vergleichsrechner, Offertentool und Zugang zur Zuriva Academy. Dein Login wurde bereits eingerichtet.",
    "Dein Mentor: Jedem Trainee wird ein erfahrener Mentor zugeteilt. Diese Person steht dir für Fragen zur Verfügung und begleitet dich in den ersten 3 Monaten. Nutze diese Chance!",
    "Dein Ziel: Innerhalb von 6 Monaten die Trainee Grundausbildung abschliessen und mit der VBV Grundausbildung beginnen. Das ist machbar wenn du regelmässig lernst.",
    "Wichtig: Du bist nicht allein! Bei Fragen steht dir Aura (unsere KI-Assistentin), dein Mentor und das ganze Zuriva-Team zur Verfügung. Trau dich zu fragen - es gibt keine dummen Fragen in der Ausbildung.",
  ], image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80" } },
  { id: "t1-6", title: "Quiz: Willkommen bei Zuriva", type: "quiz", duration: "10 Min.", completed: false, content: { type: "quiz", passingScore: 60, questions: [
    { text: "Was bedeutet 'ungebundener Vermittler'?", options: ["Angestellt bei einer Versicherung", "Unabhängig, dem Kunden verpflichtet", "Ohne Ausbildung tätig", "Nur online beratend"], correctIndex: 1, explanation: "Ein ungebundener Vermittler ist unabhängig und dem Kunden verpflichtet, nicht einem einzelnen Versicherer." },
    { text: "Aus wie vielen Lernpfaden besteht die Zuriva Academy?", options: ["3 Lernpfade", "4 Lernpfade", "5 Lernpfade", "7 Lernpfade"], correctIndex: 2, explanation: "Die Academy hat 5 Lernpfade: Trainee, VBV Grund, Krankenkasse, SachVerm, Mündlich." },
    { text: "Wie oft muss die VBV-Zertifizierung erneuert werden?", options: ["Jährlich", "Alle 2 Jahre", "Alle 5 Jahre", "Nie"], correctIndex: 1, explanation: "Die Rezertifizierung ist alle 2 Jahre nötig (ab 2026)." },
    { text: "Wie viel kostet die VBV-Grundkenntnisprüfung?", options: ["CHF 100", "CHF 200", "CHF 400", "CHF 600"], correctIndex: 2, explanation: "Die Prüfung Generelle Fähigkeiten & Kenntnisse kostet CHF 400." },
    { text: "Wo findet die mündliche VBV-Prüfung statt?", options: ["Online", "Zürich", "Bern", "Basel"], correctIndex: 2, explanation: "Die mündliche Prüfung findet vor Ort in Bern statt (30 Min., CHF 200)." },
    { text: "Mit wie vielen Versicherungspartnern arbeitet Zuriva?", options: ["3", "5", "Über 8", "Über 20"], correctIndex: 2, explanation: "Zuriva arbeitet mit über 8 führenden Schweizer Versicherern zusammen." },
    { text: "Wie viele Stunden Lernstoff hat die Academy insgesamt?", options: ["50 Stunden", "80 Stunden", "Über 110 Stunden", "200 Stunden"], correctIndex: 2, explanation: "Die Academy hat über 110 Stunden Lernstoff über alle 5 Lernpfade." },
    { text: "Was ist das Ziel des 3-Säulen-Systems?", options: ["100% des Lohns", "60-70% des letzten Einkommens", "50% Ersparnis", "Nur Grundversorgung"], correctIndex: 1, explanation: "Das Ziel des 3-Säulen-Systems ist 60-70% des letzten Einkommens im Alter." },
  ] } },
] };
export default m;
