import type { Modul } from "../../lernpfade-data";
const m: Modul = { id: "t2", title: "Die Versicherungswelt Schweiz", description: "Geschichte, Markt, Akteure und Grundprinzipien", credits: 25, lektionen: [
  { id: "t2-1", title: "Geschichte und Meilensteine", type: "interactive", duration: "15 Min.", completed: false, content: { type: "interactive", component: "AHVTimeline", description: "Die Schweizer Versicherungsgeschichte: 1826 Mobiliar (ältester Privatversicherer), 1948 AHV, 1985 BVG-Obligatorium, 1996 KVG-Obligatorium, 2024 revidiertes VAG, 2026 neue VBV-Prüfung und 13. AHV-Rente.", speakText: "Die Mobiliar wurde 1826 gegründet und ist der älteste Privatversicherer der Schweiz. 1948 kam die AHV, 1985 das BVG, 1996 die obligatorische Krankenversicherung. 2024 trat das revidierte VAG in Kraft. Und seit 2026 gilt die neue VBV-Prüfungspflicht und die 13. AHV-Rente." } },
  { id: "t2-2", title: "Marktüberblick in Zahlen", type: "interactive", duration: "15 Min.", completed: false, content: { type: "interactive", component: "MarktBarChart", description: "Der Schweizer Versicherungsmarkt: Gesamtprämienvolumen CHF 226.5 Mrd. mit 195 Privatversicherern. Die grössten: Zurich (66.1 Mrd.), Swiss Life (29.2 Mrd.), AXA (6.6 Mrd.), Mobiliar (4.8 Mrd.), Helvetia (4.5 Mrd.), Baloise (3.8 Mrd.).", speakText: "Der Schweizer Markt hat ein Gesamtprämienvolumen von 226.5 Milliarden Franken mit 195 Privatversicherern. Zurich führt mit 66.1 Milliarden, gefolgt von Swiss Life mit 29.2 und AXA mit 6.6 Milliarden." } },
  { id: "t2-3", title: "Versicherungsarten und Obligatorium", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
    { title: "3 Hauptkategorien", content: "Alle Versicherungen fallen in eine dieser Kategorien:", bulletPoints: ["Personenversicherung: Leben, Kranken, Unfall, Erwerbsunfähigkeit", "Sachversicherung: Gebäude, Hausrat, Motorfahrzeug, Transport", "Haftpflichtversicherung: Privat-, Betriebs-, Berufshaftpflicht"], speakText: "Es gibt 3 Hauptkategorien: Personenversicherung, Sachversicherung und Haftpflichtversicherung.", image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&q=80" },
    { title: "Obligatorische Versicherungen", content: "Diese Versicherungen sind in der Schweiz Pflicht:", bulletPoints: ["KVG (Krankenkasse) - für alle Einwohner", "AHV/IV/EO - für alle Erwerbstätigen, Beitrag 10.60%", "BVG (Pensionskasse) - ab CHF 22'680 Jahreslohn", "UVG (Unfallversicherung) - für alle Arbeitnehmenden", "MF-Haftpflicht - für alle Fahrzeughalter", "Gebäudeversicherung - in 19 von 26 Kantonen"], speakText: "Obligatorisch sind die Krankenkasse, AHV mit 10.60 Prozent Beitrag, BVG ab 22'680 Franken, UVG für Arbeitnehmende, Motorfahrzeug-Haftpflicht und in 19 Kantonen die Gebäudeversicherung.", image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&q=80" },
  ] } },
  { id: "t2-4", title: "Das 3-Säulen-System", type: "interactive", duration: "20 Min.", completed: false, content: { type: "interactive", component: "ThreePillarSystem", description: "1. Säule AHV: Staatlich, obligatorisch, max. CHF 2'450/Mt. 2. Säule BVG: Beruflich, ab CHF 22'680, AG+AN Beiträge. 3. Säule 3a/3b: Privat, freiwillig, max. CHF 7'258 (3a). Ziel: 60-70% des letzten Einkommens.", speakText: "Das 3-Säulen-System: Die erste Säule AHV sichert die Existenz mit maximal 2'450 Franken pro Monat. Die zweite Säule BVG erhält den Lebensstandard, obligatorisch ab 22'680 Franken Lohn. Die dritte Säule ist die private Vorsorge, mit maximal 7'258 Franken pro Jahr in der Säule 3a. Das Ziel ist 60 bis 70 Prozent des letzten Einkommens im Alter." } },
  { id: "t2-5", title: "AHV-Zahlen 2026", type: "slides", duration: "15 Min.", completed: false, content: { type: "slides", slides: [
    { title: "AHV/IV/EO 2026", content: "Die aktuellen Zahlen der 1. Säule:", bulletPoints: ["Beitragssatz: 10.60% (je 5.30% AG und AN)", "Davon: AHV 4.35%, IV 0.70%, EO 0.25%", "Maximale AHV-Rente: CHF 2'450/Monat (Einzelperson)", "Minimale AHV-Rente: CHF 1'225/Monat", "NEU 2026: 13. AHV-Rente wird erstmals im Dezember ausbezahlt", "Referenzalter Frauen: 64 Jahre 6 Monate (schrittweise auf 65)"], speakText: "Die AHV hat 2026 einen Beitragssatz von 10.60 Prozent. Die maximale Rente beträgt 2'450 Franken, die minimale 1'225 Franken. Neu wird im Dezember 2026 erstmals die 13. AHV-Rente ausbezahlt.", image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&q=80" },
    { title: "BVG 2026", content: "Berufliche Vorsorge:", bulletPoints: ["Obligatorium ab CHF 22'680 Jahreslohn", "Koordinationsabzug: CHF 26'460", "Maximal versicherter Lohn: CHF 64'260", "Altersgutschriften: 7% (25-34J), 10% (35-44J), 15% (45-54J), 18% (55-65J)", "Arbeitgeber zahlt mind. 50% der Beiträge"], speakText: "Die BVG ist obligatorisch ab 22'680 Franken. Der Koordinationsabzug beträgt 26'460 Franken. Die Altersgutschriften steigen mit dem Alter von 7 bis 18 Prozent.", image: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=1200&q=80" },
  ] } },
  { id: "t2-6", title: "BVG-Altersgutschriften", type: "interactive", duration: "10 Min.", completed: false, content: { type: "interactive", component: "BVGAltersgutschriften", description: "Die BVG-Altersgutschriften steigen mit dem Alter: 25-34 Jahre: 7%, 35-44 Jahre: 10%, 45-54 Jahre: 15%, 55-65 Jahre: 18% des koordinierten Lohns.", speakText: "Die Altersgutschriften steigen mit dem Alter. 25 bis 34 Jährige: 7 Prozent. 35 bis 44 Jährige: 10 Prozent. 45 bis 54 Jährige: 15 Prozent. 55 bis 65 Jährige: 18 Prozent." } },
  { id: "t2-7", title: "Säule 3a und Cybervorfälle", type: "slides", duration: "15 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Säule 3a 2026", content: "Private Vorsorge mit Steuervorteilen:", bulletPoints: ["Maximum 2026: CHF 7'258 (mit PK)", "Ohne PK: 20% des Nettoeinkommens, max. CHF 36'288", "Steuerersparnis in Zürich: ca. CHF 1'800-2'500/Jahr", "Bezug: Frühestens 5 Jahre vor AHV-Alter", "Säule 3b: Keine Limite, keine Steuerabzüge"], speakText: "Die Säule 3a erlaubt maximal 7'258 Franken pro Jahr und spart in Zürich 1'800 bis 2'500 Franken Steuern. Der Bezug ist frühestens 5 Jahre vor dem AHV-Alter möglich.", image: "https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=1200&q=80" },
    { title: "Trend: Cybervorfälle Nr. 1 Risiko", content: "Cybervorfälle sind laut aktuellen Studien das grösste Risiko weltweit:", bulletPoints: ["10 Prozentpunkte Vorsprung vor dem zweitgrössten Risiko", "Cyber-Versicherung ist das am schnellsten wachsende Segment", "Auch KMU sind betroffen - nicht nur Grossunternehmen", "Wichtig für deine Beratung: Kunden auf Cyber-Risiken aufmerksam machen"], speakText: "Cybervorfälle sind das Nummer 1 Risiko weltweit mit 10 Prozentpunkten Vorsprung. Die Cyber-Versicherung wächst am schnellsten. Auch KMU sind betroffen.", image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80" },
  ] } },
  { id: "t2-8", title: "Quiz: Versicherungswelt", type: "quiz", duration: "10 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
    { text: "Welcher ist der älteste Privatversicherer der Schweiz?", options: ["Zurich", "Helvetia", "Mobiliar", "Baloise"], correctIndex: 2, explanation: "In der Timeline hast du gelernt: Die Mobiliar wurde 1826 gegründet." },
    { text: "Wie hoch ist das Prämienvolumen des Schweizer Markts?", options: ["CHF 50 Mrd.", "CHF 120 Mrd.", "CHF 226.5 Mrd.", "CHF 500 Mrd."], correctIndex: 2, explanation: "Im Marktüberblick gezeigt: CHF 226.5 Mrd." },
    { text: "Welche 3 Hauptkategorien von Versicherungen gibt es?", options: ["Auto, Haus, Leben", "Personen, Sach, Haftpflicht", "Privat, Gewerbe, Staat", "Oblig., Freiwillig, Zusatz"], correctIndex: 1, explanation: "Lektion 'Versicherungsarten': Personen-, Sach- und Haftpflichtversicherung." },
    { text: "Ab welchem Lohn ist BVG obligatorisch?", options: ["CHF 15'000", "CHF 22'680", "CHF 30'000", "CHF 50'000"], correctIndex: 1, explanation: "Im Slide 'Obligatorische Versicherungen' gelernt: Ab CHF 22'680." },
    { text: "Was ist das Ziel des 3-Säulen-Systems?", options: ["100% des Lohns", "60-70% des letzten Einkommens", "50% Ersparnis", "Nur Existenzsicherung"], correctIndex: 1, explanation: "Im 3-Säulen-System gelernt: Ziel ist 60-70% des letzten Einkommens." },
    { text: "Maximale AHV-Rente 2026 (Einzelperson)?", options: ["CHF 1'225/Mt.", "CHF 2'450/Mt.", "CHF 3'500/Mt.", "CHF 5'000/Mt."], correctIndex: 1, explanation: "Slide 'AHV-Zahlen 2026': Max. CHF 2'450/Mt." },
    { text: "Wie hoch ist der AHV-Beitragssatz 2026?", options: ["8.70%", "10.60%", "12.40%", "15%"], correctIndex: 1, explanation: "Slide 'AHV/IV/EO 2026': 10.60%, je 5.30% AG und AN." },
    { text: "Wie hoch ist der maximale 3a-Beitrag 2026 (mit PK)?", options: ["CHF 5'000", "CHF 7'258", "CHF 10'000", "CHF 36'288"], correctIndex: 1, explanation: "Slide 'Säule 3a 2026': CHF 7'258 mit PK." },
    { text: "Was ist das Nr. 1 Risiko weltweit?", options: ["Naturkatastrophen", "Cybervorfälle", "Pandemien", "Inflation"], correctIndex: 1, explanation: "Slide 'Trend: Cybervorfälle': Nr. 1 mit 10 Prozentpunkten Vorsprung." },
    { text: "BVG-Altersgutschrift für 45-54-Jährige?", options: ["7%", "10%", "15%", "18%"], correctIndex: 2, explanation: "Im Balkendiagramm 'BVG-Altersgutschriften' gelernt: 15%." },
  ] } },
] };
export default m;
