import type { Modul } from "../../lernpfade-data";
const m: Modul = { id: "t2", title: "Die Versicherungswelt Schweiz", description: "Geschichte, Markt, Akteure und Grundprinzipien", credits: 25, lektionen: [
  { id: "t2-1", title: "Geschichte der Versicherung", type: "interactive", duration: "15 Min.", completed: false, content: { type: "interactive", component: "AHVTimeline", description: "Die wichtigsten Meilensteine der Schweizer Versicherungsgeschichte im Zeitstrahl.", speakText: "Die Geschichte der Versicherung in der Schweiz reicht weit zurück. 1826 wurde die Mobiliar als ältester Privatversicherer gegründet. 1948 kam die AHV, 1985 das BVG-Obligatorium, 1996 die obligatorische Krankenversicherung. 2024 trat das revidierte VAG in Kraft, und seit 2026 gilt die neue VBV-Prüfungspflicht und die 13. AHV-Rente." } },
  { id: "t2-2", title: "Der Schweizer Markt in Zahlen", type: "interactive", duration: "20 Min.", completed: false, content: { type: "interactive", component: "MarktBarChart", description: "Die grössten Schweizer Versicherer nach Bruttoprämienvolumen in Milliarden CHF. Der Gesamtmarkt beträgt CHF 226.5 Milliarden.", speakText: "Der Schweizer Versicherungsmarkt hat ein Gesamtprämienvolumen von 226.5 Milliarden Franken. Die Zurich Insurance Group führt mit 66.1 Milliarden, gefolgt von Swiss Life mit 29.2 Milliarden und AXA Schweiz mit 6.6 Milliarden. Die Mobiliar liegt bei 4.8 und Helvetia bei 4.5 Milliarden." } },
  { id: "t2-3", title: "Trends 2026", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Was den Markt bewegt", content: "Die wichtigsten Trends im Schweizer Versicherungsmarkt:", bulletPoints: ["Cybervorfälle: Nr. 1 Risiko weltweit mit 10 Prozentpunkten Vorsprung", "Digitale Transformation: Online-Schadenmeldung, Self-Service-Portale", "DigiSanté: Bund setzt auf Digitalisierung des Gesundheitswesens", "Klimawandel: Zunehmende Elementarschäden, steigende Prämien", "KI-Integration: Chatbots, automatisierte Schadenabwicklung", "13. AHV-Rente: Erstmals im Dezember 2026 ausbezahlt"], speakText: "Cybervorfälle sind das Nummer 1 Risiko weltweit. Die Digitalisierung treibt die Branche voran. Der Klimawandel führt zu mehr Elementarschäden. Und die 13. AHV-Rente wird erstmals 2026 ausbezahlt.", image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80" },
    { title: "Versicherungsarten", content: "Drei Hauptkategorien von Versicherungen:", bulletPoints: ["Personenversicherung: Leben, Kranken, Unfall, Erwerbsunfähigkeit", "Sachversicherung: Gebäude, Hausrat, Motorfahrzeug, Transport", "Haftpflichtversicherung: Privat-, Betriebs-, Berufshaftpflicht", "Weitere: Rechtsschutz, Reise, Cyber, Kredit"], speakText: "Es gibt drei Hauptkategorien. Personenversicherungen wie Leben und Kranken. Sachversicherungen wie Gebäude und Motorfahrzeug. Und Haftpflichtversicherungen.", image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&q=80" },
    { title: "Obligatorische Versicherungen", content: "Diese Versicherungen sind in der Schweiz Pflicht:", bulletPoints: ["KVG Grundversicherung (Krankenkasse) - für alle", "AHV/IV/EO (1. Säule) - für alle Erwerbstätigen", "BVG (2. Säule) - ab CHF 22'680 Jahreslohn", "UVG (Unfallversicherung) - für alle Arbeitnehmenden", "Motorfahrzeug-Haftpflicht - für alle Fahrzeughalter", "Gebäudeversicherung - in 19 Kantonen", "Berufshaftpflicht - für bestimmte Berufe"], speakText: "Obligatorisch sind: KVG, AHV, BVG ab 22'680 Franken, UVG, Motorfahrzeug-Haftpflicht und in 19 Kantonen die Gebäudeversicherung.", image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&q=80" },
  ] } },
  { id: "t2-4", title: "Das 3-Säulen-System", type: "interactive", duration: "25 Min.", completed: false, content: { type: "interactive", component: "ThreePillarSystem", description: "Das Schweizer 3-Säulen-System ist weltweit einzigartig. Die 1. Säule (AHV) sichert die Existenz, die 2. Säule (BVG) den Lebensstandard und die 3. Säule die individuelle Ergänzung.", speakText: "Das Schweizer 3-Säulen-System besteht aus drei Teilen. Die erste Säule ist die AHV für die Existenzsicherung. Der Beitragssatz beträgt 10.60 Prozent, die maximale Rente 2'450 Franken pro Monat. Neu 2026 kommt die 13. AHV-Rente dazu. Die zweite Säule ist die berufliche Vorsorge über die Pensionskasse. Sie ist obligatorisch ab 22'680 Franken Jahreslohn. Die Altersgutschriften steigen von 7 Prozent für 25 bis 34 Jährige bis 18 Prozent für 55 bis 65 Jährige. Die dritte Säule ist die private Vorsorge. Die Säule 3a erlaubt maximal 7'258 Franken pro Jahr und bringt eine Steuerersparnis von 1'800 bis 2'500 Franken in Zürich." } },
  { id: "t2-5", title: "BVG-Altersgutschriften", type: "interactive", duration: "15 Min.", completed: false, content: { type: "interactive", component: "BVGAltersgutschriften", description: "Die BVG-Altersgutschriften steigen mit dem Alter. Je älter du bist, desto mehr wird in deine Pensionskasse eingezahlt.", speakText: "Die BVG-Altersgutschriften steigen mit dem Alter. Für 25 bis 34 Jährige sind es 7 Prozent des koordinierten Lohns. Für 35 bis 44 Jährige 10 Prozent. Für 45 bis 54 Jährige 15 Prozent. Und für 55 bis 65 Jährige 18 Prozent. Der Arbeitgeber muss mindestens 50 Prozent der Beiträge zahlen." } },
  { id: "t2-6", title: "Sozialversicherungen Überblick", type: "interactive", duration: "20 Min.", completed: false, content: { type: "interactive", component: "SozialversicherungDonut", description: "Die Gesamtbelastung durch Sozialversicherungen für Arbeitgeber und Arbeitnehmer zusammen beträgt rund 29% des Bruttolohns.", speakText: "Die Sozialversicherungen belasten Arbeitgeber und Arbeitnehmer zusammen mit rund 29 Prozent des Bruttolohns. Den grössten Anteil hat die BVG mit rund 12 Prozent, gefolgt von der AHV, IV und EO mit 10.6 Prozent. Dazu kommen ALV mit 2.2 Prozent, UVG mit 2.3 Prozent und Familienzulagen mit rund 2 Prozent." } },
  { id: "t2-7", title: "Quiz: Versicherungswelt", type: "quiz", duration: "15 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
    { text: "Wie hoch ist das Prämienvolumen des Schweizer Versicherungsmarkts?", options: ["CHF 50 Mrd.", "CHF 120 Mrd.", "CHF 226.5 Mrd.", "CHF 500 Mrd."], correctIndex: 2, explanation: "Das Gesamtprämienvolumen beträgt CHF 226.5 Mrd. (2024)." },
    { text: "Was ist das Nr. 1 Risiko weltweit?", options: ["Naturkatastrophen", "Cybervorfälle", "Pandemien", "Inflation"], correctIndex: 1, explanation: "Cybervorfälle führen die globale Risikotabelle an." },
    { text: "AHV-Beitragssatz 2026?", options: ["8.70%", "10.60%", "12.40%", "15.00%"], correctIndex: 1, explanation: "10.60%, je 5.30% AG und AN." },
    { text: "Was ist neu bei der AHV ab 2026?", options: ["Rentenalter 67", "13. AHV-Rente", "AHV wird abgeschafft", "Beitragssenkung"], correctIndex: 1, explanation: "Die 13. AHV-Rente wird erstmals im Dezember 2026 ausbezahlt." },
    { text: "Säule 3a Maximum 2026 mit PK?", options: ["CHF 5'000", "CHF 7'258", "CHF 10'000", "CHF 36'288"], correctIndex: 1, explanation: "CHF 7'258 für Angestellte mit Pensionskasse." },
    { text: "Ab welchem Lohn ist BVG obligatorisch?", options: ["CHF 15'000", "CHF 22'680", "CHF 30'000", "CHF 50'000"], correctIndex: 1, explanation: "Ab CHF 22'680 Jahreslohn." },
    { text: "Welche BVG-Altersgutschrift gilt für 45-54-Jährige?", options: ["7%", "10%", "15%", "18%"], correctIndex: 2, explanation: "Für 45-54-Jährige: 15% des koordinierten Lohns." },
    { text: "Welcher ist der älteste Privatversicherer der Schweiz?", options: ["Zurich", "Helvetia", "Mobiliar", "Baloise"], correctIndex: 2, explanation: "Die Mobiliar wurde 1826 gegründet." },
  ] } },
] };
export default m;
