import type { Modul } from "../../lernpfade-data";
const m: Modul = { id: "t2", title: "Die Versicherungswelt Schweiz", description: "Geschichte, Markt, Akteure und Grundprinzipien", credits: 25, lektionen: [
  { id: "t2-1", title: "Geschichte der Versicherung", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Von den Anfängen bis heute", content: "Die Versicherung hat eine lange Geschichte:", bulletPoints: ["1347: Erste Seeversicherungspolice in Genua", "1666: Brand von London - erste Feuerversicherungen", "1826: Gründung der Mobiliar (ältester CH-Privatversicherer)", "1948: Einführung der AHV", "1985: BVG-Obligatorium", "1996: KVG-Obligatorium", "2024: Revidiertes VAG tritt in Kraft"], speakText: "Die Geschichte der Versicherung reicht bis 1347 zurück. In der Schweiz wurde 1826 die Mobiliar gegründet. Meilensteine waren die AHV 1948, das BVG 1985 und das KVG 1996." },
  ] } },
  { id: "t2-2", title: "Der Schweizer Markt 2026", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Marktüberblick", content: "Einer der wichtigsten Märkte weltweit:", bulletPoints: ["Gesamtprämienvolumen: CHF 226.5 Mrd.", "195 Privatversicherer in 5 Versicherungszweigen", "Höchste Versicherungsdichte weltweit (Prämien pro Kopf)", "Über 50'000 Beschäftigte in der Branche"], speakText: "Der Schweizer Versicherungsmarkt hat ein Prämienvolumen von 226.5 Milliarden Franken mit 195 Privatversicherern." },
    { title: "Die Grössten", content: "Top Versicherer nach Prämienvolumen:", bulletPoints: ["1. Zurich Insurance: CHF 66.1 Mrd.", "2. Swiss Life: CHF 29.2 Mrd.", "3. AXA Schweiz: CHF 6.6 Mrd.", "4. Mobiliar: CHF 4.8 Mrd.", "5. Helvetia: CHF 4.5 Mrd.", "6. Baloise: CHF 3.8 Mrd."], speakText: "Die grössten Versicherer der Schweiz sind Zurich mit 66.1 Milliarden, Swiss Life mit 29.2 Milliarden und AXA mit 6.6 Milliarden." },
    { title: "Trends 2026", content: "Was den Markt bewegt:", bulletPoints: ["Cybervorfälle: Nr. 1 Risiko weltweit", "Digitalisierung: Online-Schadenmeldung, Self-Service", "Klimawandel: Mehr Elementarschäden", "KI in der Beratung und Schadenabwicklung", "13. AHV-Rente: Erstmals Dezember 2026"], speakText: "Cybervorfälle sind das Nummer 1 Risiko weltweit. Die Digitalisierung und der Klimawandel prägen den Markt." },
  ] } },
  { id: "t2-3", title: "Grundprinzipien der Versicherung", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Was ist Versicherung?", content: "Risikoübertragung gegen Prämie:", bulletPoints: ["Versicherungsnehmer (VN): Die versicherte Person", "Versicherer: Das Versicherungsunternehmen", "Prämie: Der Preis für den Schutz", "Leistung: Die Zahlung im Schadenfall", "Police: Der Versicherungsvertrag", "Gesetz der grossen Zahl: Viele teilen das Risiko"], speakText: "Versicherung ist die Übertragung eines Risikos auf einen Risikoträger gegen eine Prämie. Das Gesetz der grossen Zahl macht es möglich." },
    { title: "Versicherungsarten", content: "Drei Hauptkategorien:", bulletPoints: ["Personenversicherung: Leben, Kranken, Unfall", "Sachversicherung: Gebäude, Hausrat, MF", "Haftpflichtversicherung: Privat, Betrieb, Beruf", "Weitere: Rechtsschutz, Reise, Cyber"], speakText: "Es gibt Personenversicherungen, Sachversicherungen und Haftpflichtversicherungen." },
    { title: "Obligatorische Versicherungen CH", content: "Diese sind Pflicht:", bulletPoints: ["KVG Grundversicherung (Krankenkasse)", "AHV/IV/EO (1. Säule)", "BVG (2. Säule, ab CHF 22'680)", "UVG (Unfallversicherung Arbeitnehmer)", "MF-Haftpflicht (Motorfahrzeug)", "Gebäudeversicherung (19 Kantone)"], speakText: "In der Schweiz sind unter anderem die KVG Grundversicherung, AHV, BVG, UVG und die Motorfahrzeug-Haftpflicht obligatorisch." },
  ] } },
  { id: "t2-4", title: "Das 3-Säulen-System", type: "slides", duration: "30 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Überblick", content: "Weltweit einzigartiges Vorsorgesystem:", bulletPoints: ["1. Säule: AHV/IV - Existenzsicherung (staatlich)", "2. Säule: BVG/PK - Lebensstandard (beruflich)", "3. Säule: 3a/3b - Individuelle Ergänzung (privat)", "Ziel: 60-70% des letzten Einkommens im Alter"], speakText: "Das 3-Säulen-System der Schweiz besteht aus der staatlichen AHV, der beruflichen Vorsorge und der privaten Vorsorge." },
    { title: "1. Säule: AHV 2026", content: "Aktuelle Zahlen:", bulletPoints: ["Beitrag: 10.60% (je 5.30% AG/AN)", "Max. Rente: CHF 2'450/Mt. (Einzelperson)", "Min. Rente: CHF 1'225/Mt.", "NEU: 13. AHV-Rente ab Dezember 2026", "Referenzalter Frauen: 64 J. 6 Mt. (schrittweise auf 65)"], speakText: "Die AHV hat einen Beitragssatz von 10.60 Prozent. Die maximale Rente beträgt 2'450 Franken. Neu 2026: die 13. AHV-Rente." },
    { title: "2. Säule: BVG 2026", content: "Berufliche Vorsorge:", bulletPoints: ["Obligatorium ab CHF 22'680 Jahreslohn", "Koordinationsabzug: CHF 26'460", "Altersgutschriften: 7% (25-34J) bis 18% (55-65J)", "AG zahlt mind. 50% der Beiträge", "UVG-Höchstlohn: CHF 148'200"], speakText: "Die zweite Säule ist obligatorisch ab 22'680 Franken Jahreslohn. Die Altersgutschriften steigen von 7 auf 18 Prozent." },
    { title: "3. Säule 2026", content: "Private Vorsorge:", bulletPoints: ["3a Maximum: CHF 7'258 (mit PK)", "3a ohne PK: 20% Nettoeinkommen, max. CHF 36'288", "Steuerersparnis: CHF 1'800-2'500/Jahr (Zürich)", "Bezug: Frühestens 5 Jahre vor AHV-Alter", "3b: Keine Limite, keine Steuerabzüge"], speakText: "Die Säule 3a erlaubt maximal 7'258 Franken pro Jahr. Die Steuerersparnis in Zürich beträgt 1'800 bis 2'500 Franken." },
  ] } },
  { id: "t2-5", title: "Quiz: Versicherungswelt", type: "quiz", duration: "15 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
    { text: "Wie hoch ist das Prämienvolumen des Schweizer Markts?", options: ["CHF 50 Mrd.", "CHF 120 Mrd.", "CHF 226.5 Mrd.", "CHF 500 Mrd."], correctIndex: 2, explanation: "CHF 226.5 Mrd. (2024)." },
    { text: "Was ist das Nr. 1 Risiko weltweit?", options: ["Naturkatastrophen", "Cybervorfälle", "Pandemien", "Inflation"], correctIndex: 1, explanation: "Cybervorfälle führen die Risikotabelle an." },
    { text: "Wie hoch ist der AHV-Beitragssatz 2026?", options: ["8.70%", "10.60%", "12.40%", "15.00%"], correctIndex: 1, explanation: "10.60%, je 5.30% AG und AN." },
    { text: "Was ist neu ab 2026 bei der AHV?", options: ["Rentenalter 67", "13. AHV-Rente", "AHV-Abschaffung", "Beitragssenkung"], correctIndex: 1, explanation: "Die 13. AHV-Rente wird erstmals im Dezember 2026 ausbezahlt." },
    { text: "Säule 3a Maximum 2026 (mit PK)?", options: ["CHF 5'000", "CHF 7'258", "CHF 10'000", "CHF 36'288"], correctIndex: 1, explanation: "CHF 7'258 für Erwerbstätige mit Pensionskasse." },
    { text: "Ab welchem Lohn ist BVG obligatorisch?", options: ["CHF 15'000", "CHF 22'680", "CHF 30'000", "CHF 50'000"], correctIndex: 1, explanation: "Ab CHF 22'680 Jahreslohn." },
  ] } },
] };
export default m;
