import type { Modul } from "../../lernpfade-data";
const m: Modul = { id: "t3", title: "Kundenumgang Basics", description: "Erster Kontakt, Kommunikation, schwierige Situationen", credits: 25, lektionen: [
  { id: "t3-1", title: "Der erste Eindruck", type: "slides", duration: "15 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Die ersten 7 Sekunden", content: "Studien zeigen: Der erste Eindruck entsteht in nur 7 Sekunden und ist danach kaum noch korrigierbar.", bulletPoints: ["Blickkontakt herstellen und natürlich lächeln", "Fester Händedruck - nicht zu stark, nicht zu schwach", "Aufrechte Haltung signalisiert Kompetenz und Selbstvertrauen", "Gepflegtes Erscheinungsbild: Business Casual als Minimum", "Pünktlichkeit: 5 Minuten zu früh ist optimal", "Visitenkarte bereithalten und beim Vorstellen überreichen"], speakText: "Der erste Eindruck entsteht in 7 Sekunden. Achte auf Blickkontakt, einen festen Händedruck, aufrechte Haltung und ein gepflegtes Erscheinungsbild. Sei immer pünktlich.", image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1200&q=80" },
    { title: "Begrüssung und Smalltalk", content: "Die ersten 2-3 Minuten entscheiden über den Gesprächsverlauf:", bulletPoints: ["Stelle dich vor: Vorname, Nachname und 'Zuriva'", "Bedanke dich: 'Vielen Dank für Ihre Zeit'", "Smalltalk: Wetter, Anreise, Büro des Kunden (2-3 Minuten)", "NICHT ansprechen: Politik, Religion, Gehalt", "Überleitung: 'Darf ich zum Anlass unseres Treffens kommen?'"], speakText: "Stelle dich klar vor und bedanke dich für die Zeit. Führe 2-3 Minuten Smalltalk über neutrale Themen. Vermeide Politik und Religion. Leite dann professionell zum Geschäft über.", image: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1200&q=80" },
  ] } },
  { id: "t3-2", title: "Professionelle Kommunikation", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Verbale Kommunikation", content: "Was du sagst und wie du es sagst macht den Unterschied:", bulletPoints: ["Einfache, klare Sprache - Fachbegriffe immer erklären", "Kurze Sätze statt Monologe - max. 30 Sekunden am Stück reden", "Tempo anpassen: Nicht zu schnell, nicht zu langsam", "Pausen bewusst einsetzen - gibt dem Kunden Raum zum Denken", "Fragen stellen statt Vorträge halten"], speakText: "Sprich einfach und klar. Erkläre Fachbegriffe immer. Halte dich kurz und stelle Fragen statt Vorträge zu halten.", image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=1200&q=80" },
    { title: "Körpersprache", content: "Über 55% der Kommunikation ist nonverbal:", bulletPoints: ["Offene Haltung: Arme nicht verschränken", "Augenkontakt: 60-70% der Gesprächszeit", "Nicken zeigt Verständnis und Aufmerksamkeit", "Spiegeln: Körperhaltung des Kunden dezent nachahmen", "Notizen machen: Zeigt Interesse und Wertschätzung"], speakText: "Über 55 Prozent der Kommunikation ist nonverbal. Achte auf offene Haltung, halte Augenkontakt 60 bis 70 Prozent der Zeit und mache Notizen.", image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1200&q=80" },
    { title: "Telefon und E-Mail", content: "Professionelle Kommunikation auf Distanz:", bulletPoints: ["Telefon: Lächle beim Sprechen - man hört es in der Stimme", "Melde dich: 'Guten Tag, [Vorname Nachname] von Zuriva'", "E-Mail: Antwort innert 24 Stunden", "E-Mail Signatur: Name, Funktion, Telefon, Zuriva Logo", "Nach jedem Gespräch: Schriftliche Zusammenfassung per Mail senden"], speakText: "Am Telefon immer lächeln, das hört man. Melde dich mit vollem Namen und Firma. E-Mails innert 24 Stunden beantworten. Nach jedem Gespräch eine schriftliche Zusammenfassung senden.", image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&q=80" },
  ] } },
  { id: "t3-3", title: "Schwierige Situationen", type: "text", duration: "15 Min.", completed: false, content: { type: "text", paragraphs: [
    "Im Kundenkontakt wirst du auf schwierige Situationen treffen. Hier die 4 häufigsten und wie du damit umgehst:",
    "1) Unzufriedene Kunden: Zuerst zuhören ohne zu unterbrechen. Dann Verständnis zeigen: 'Ich verstehe Ihren Ärger.' Sich entschuldigen und eine konkrete Lösung anbieten. Immer die Beschwerde dokumentieren und nachfassen.",
    "2) Kunden die 'Nein' sagen: Respektiere die Entscheidung. Frage höflich nach dem Grund. Hinterlasse einen positiven Eindruck. Sende eine Dankes-Mail: 'Danke für Ihre Zeit, ich stehe gerne zur Verfügung.'",
    "3) Preisdiskussionen: Argumentiere nie über den Preis, sondern über den Wert und Nutzen. Zeige auf, was im Schadenfall ohne Versicherung passiert. Nutze den Vergleich: 'Das sind weniger als CHF 2 pro Tag.'",
    "4) Vertraulichkeit: Kundeninformationen sind streng vertraulich. Sprich nie über andere Kunden. Das Datenschutzgesetz (DSG) sieht Bussen bis CHF 250'000 vor.",
  ], image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=1200&q=80" } },
  { id: "t3-4", title: "Quiz: Kundenumgang", type: "quiz", duration: "10 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
    { text: "Wie viele Sekunden dauert der erste Eindruck?", options: ["3 Sekunden", "7 Sekunden", "30 Sekunden", "2 Minuten"], correctIndex: 1, explanation: "Slide 'Die ersten 7 Sekunden': Der erste Eindruck entsteht in 7 Sekunden." },
    { text: "Was sollte man beim Smalltalk NICHT ansprechen?", options: ["Das Wetter", "Die Anreise", "Politik und Religion", "Das Büro des Kunden"], correctIndex: 2, explanation: "Slide 'Begrüssung': Politik und Religion sind Tabu-Themen." },
    { text: "Wie viel Prozent der Kommunikation ist nonverbal?", options: ["10%", "30%", "Über 55%", "90%"], correctIndex: 2, explanation: "Slide 'Körpersprache': Über 55% der Kommunikation ist nonverbal." },
    { text: "Wie lange sollte man Augenkontakt halten?", options: ["10-20% der Zeit", "30-40% der Zeit", "60-70% der Zeit", "100% der Zeit"], correctIndex: 2, explanation: "Slide 'Körpersprache': Augenkontakt 60-70% der Gesprächszeit." },
    { text: "Wie schnell solltest du auf E-Mails antworten?", options: ["Sofort", "Innert 24 Stunden", "Innert 1 Woche", "Wenn Zeit ist"], correctIndex: 1, explanation: "Slide 'Telefon und E-Mail': Antwort innert 24 Stunden." },
    { text: "Was machst du nach jedem Kundengespräch?", options: ["Nichts", "Schriftliche Zusammenfassung senden", "3 Tage warten", "Anrufen"], correctIndex: 1, explanation: "Slide 'Telefon und E-Mail': Nach jedem Gespräch schriftliche Zusammenfassung senden." },
    { text: "Wie reagierst du bei Preisdiskussionen?", options: ["Sofort Rabatt geben", "Über den Wert und Nutzen argumentieren", "Gespräch beenden", "Teureres Produkt anbieten"], correctIndex: 1, explanation: "Text 'Schwierige Situationen': Über den Wert argumentieren, nicht über den Preis." },
    { text: "Wie hoch ist die maximale DSG-Busse?", options: ["CHF 10'000", "CHF 50'000", "CHF 250'000", "CHF 1 Mio."], correctIndex: 2, explanation: "Text 'Schwierige Situationen': DSG-Bussen bis CHF 250'000." },
  ] } },
] };
export default m;
