import type { Modul } from "../../lernpfade-data";
const m: Modul = { id: "t4", title: "Produkte Grundwissen", description: "Überblick aller Versicherungsprodukte", credits: 25, lektionen: [
  { id: "t4-1", title: "Personenversicherungen", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Lebensversicherung", content: "Schutz für das Leben und die Vorsorge:", bulletPoints: ["Risikolebensversicherung: Reiner Todesfallschutz, tiefe Prämie", "Gemischte LV: Spar- + Risikokomponente kombiniert", "Fondsgebundene LV: Anlage in Investmentfonds", "Säule 3a: Steuerbegünstigt, max. CHF 7'258/Jahr (2026)", "Erwerbsunfähigkeitsversicherung: Schutz bei Invalidität"], speakText: "Lebensversicherungen umfassen Risiko-, gemischte und fondsgebundene Policen. Die Säule 3a bietet Steuervorteile bis 7'258 Franken.", image: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=1200&q=80" },
    { title: "UVG - Unfallversicherung", content: "Obligatorisch für alle Arbeitnehmenden:", bulletPoints: ["Berufsunfall (BU): Prämie zahlt der Arbeitgeber", "Nichtberufsunfall (NBU): Prämie zahlt der Arbeitnehmer", "Wichtig: NBU gilt erst ab 8 Wochenstunden beim gleichen AG", "Unter 8h: Unfälle über KVG gedeckt (mit Franchise!)", "UVG-Taggeld: 80% des Lohns, KEINE Franchise", "UVG-Höchstlohn 2026: CHF 148'200"], speakText: "Die UVG-Unfallversicherung ist obligatorisch. Berufsunfälle zahlt der Arbeitgeber, Nichtberufsunfälle der Arbeitnehmer. NBU gilt erst ab 8 Wochenstunden. Das UVG zahlt 80 Prozent des Lohns ohne Franchise.", image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=1200&q=80" },
    { title: "Krankenversicherung", content: "KVG Grundversicherung und Zusätze:", bulletPoints: ["KVG: Obligatorisch für alle, Aufnahmepflicht, freie Kassenwahl", "Franchise: CHF 300 (min.) bis CHF 2'500 (max.)", "Selbstbehalt: 10%, max. CHF 700/Jahr", "Zusatzversicherungen (VVG): Kasse DARF ablehnen!", "Spitalzusatz: Halbprivat, Privat", "KTG: Krankentaggeld bei Krankheit (nicht obligatorisch)"], speakText: "Die KVG Grundversicherung ist obligatorisch mit Aufnahmepflicht. Die Franchise liegt zwischen 300 und 2'500 Franken. Zusatzversicherungen unterliegen dem VVG und die Kasse darf ablehnen.", image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=1200&q=80" },
  ] } },
  { id: "t4-2", title: "Sachversicherungen", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Gebäude und Hausrat", content: "Schutz für Heim und Besitz:", bulletPoints: ["Gebäudeversicherung: In 19 Kantonen Monopol, in 7 GUSTAVO-Kantonen frei", "GUSTAVO = Genf, Uri, Schwyz, Tessin, AI, Wallis, Obwalden", "Hausratversicherung: Alles Bewegliche im Haushalt", "Gedeckt: Feuer, Einbruch (Einbruchspuren nötig!), Wasser, Elementar", "Unterversicherung = proportionale Leistungskürzung!"], speakText: "Die Gebäudeversicherung ist in 19 Kantonen ein Monopol. In den 7 GUSTAVO-Kantonen kannst du als Vermittler aktiv Gebäudeversicherungen vermitteln. Bei Unterversicherung wird die Leistung proportional gekürzt.", image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80" },
    { title: "Haftpflicht und Motorfahrzeug", content: "Wenn du Schaden verursachst oder dein Auto schützen willst:", bulletPoints: ["Privathaftpflicht: NICHT obligatorisch, aber dringend empfohlen", "Typische Deckung: CHF 5-10 Mio.", "MF-Haftpflicht: Obligatorisch, min. CHF 5 Mio. Personenschäden", "Teilkasko: Feuer, Diebstahl, Glasbruch, Elementar", "Vollkasko: Teilkasko + selbst verschuldete Kollision", "Bonussystem: Bis 70% Rabatt für schadenfreie Jahre"], speakText: "Die Privathaftpflicht ist nicht obligatorisch aber dringend empfohlen. Die MF-Haftpflicht ist obligatorisch mit mindestens 5 Millionen Deckung. Die Vollkasko deckt zusätzlich selbst verschuldete Kollisionsschäden.", image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=1200&q=80" },
  ] } },
  { id: "t4-3", title: "Unsere 8 Versicherungspartner", type: "slides", duration: "15 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Partner im Überblick", content: "Mit diesen Versicherern arbeiten wir zusammen:", bulletPoints: ["Helvetia: Sach, Haftpflicht, Motorfahrzeug", "Zurich: Umfassend, inkl. Cyber-Versicherung", "Swiss Life: Marktführer Leben/Vorsorge", "AXA: Grösster Allbranchenversicherer (CHF 6.6 Mrd.)", "Mobiliar: Ältester Privatversicherer, Schadengeschäft", "CSS: Spezialist Krankenversicherung", "Baloise: Privat- und KMU-Kunden", "Allianz: International, Leben und Vorsorge"], speakText: "Wir arbeiten mit Helvetia, Zurich, Swiss Life, AXA, Mobiliar, CSS, Baloise und Allianz zusammen. AXA ist der grösste Allbranchenversicherer mit 6.6 Milliarden Prämienvolumen.", image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80" },
  ] } },
  { id: "t4-4", title: "Quiz: Produkte", type: "quiz", duration: "10 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
    { text: "Ab wann gilt die NBU-Versicherung (UVG)?", options: ["Immer", "Ab 8 Wochenstunden beim gleichen AG", "Ab 20 Wochenstunden", "Ab 40 Wochenstunden"], correctIndex: 1, explanation: "Slide 'UVG': NBU gilt erst ab 8 Wochenstunden beim gleichen Arbeitgeber." },
    { text: "Wie hoch ist das UVG-Taggeld?", options: ["60%", "70%", "80%", "100%"], correctIndex: 2, explanation: "Slide 'UVG': UVG-Taggeld beträgt 80% des Lohns." },
    { text: "Hat das UVG eine Franchise?", options: ["Ja, CHF 300", "Ja, CHF 2'500", "Nein, keine Franchise", "Ja, CHF 1'000"], correctIndex: 2, explanation: "Slide 'UVG': UVG hat KEINE Franchise." },
    { text: "Was bedeutet GUSTAVO?", options: ["Ein Versicherungsprodukt", "7 Kantone ohne Gebäudeversicherungsmonopol", "Eine Prämienformel", "Ein Gesetz"], correctIndex: 1, explanation: "Slide 'Gebäude und Hausrat': GUSTAVO = GE, UR, SZ, TI, AI, VS, OW." },
    { text: "Ist die Privathaftpflicht obligatorisch?", options: ["Ja", "Nein, aber dringend empfohlen", "Nur für Firmen", "Nur ab CHF 100'000 Vermögen"], correctIndex: 1, explanation: "Slide 'Haftpflicht': Nicht obligatorisch, aber dringend empfohlen." },
    { text: "Was deckt die Vollkasko ZUSÄTZLICH zur Teilkasko?", options: ["Diebstahl", "Glasbruch", "Selbst verschuldete Kollision", "Elementarschäden"], correctIndex: 2, explanation: "Slide 'Haftpflicht und MF': Vollkasko = Teilkasko + selbst verschuldete Kollision." },
    { text: "Dürfen Kassen bei KVG-Zusatzversicherungen ablehnen?", options: ["Nein, Aufnahmepflicht", "Ja, nach Gesundheitsprüfung", "Nur über 65-Jährige", "Nie"], correctIndex: 1, explanation: "Slide 'Krankenversicherung': Zusatzversicherungen (VVG) - Kasse DARF ablehnen." },
    { text: "Wer ist der grösste Allbranchenversicherer der Schweiz?", options: ["Mobiliar", "Helvetia", "AXA", "Zurich"], correctIndex: 2, explanation: "Slide 'Partner': AXA ist der grösste Allbranchenversicherer (CHF 6.6 Mrd.)." },
  ] } },
] };
export default m;
