import type { Modul } from "../../lernpfade-data";
const m: Modul = { id: "t4", title: "Produkte Grundwissen", description: "Überblick aller Versicherungsprodukte die du vermitteln wirst", credits: 25, lektionen: [
  { id: "t4-1", title: "Personenversicherungen Überblick", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Lebensversicherung", content: "Schutz für das wichtigste Gut - das Leben:", bulletPoints: ["Risikolebensversicherung: Reiner Todesfallschutz, tiefe Prämie", "Gemischte LV: Spar- und Risikokomponente kombiniert", "Fondsgebundene LV: Anlage in Investmentfonds", "Säule 3a: Steuerbegünstigt, max. CHF 7'258/Jahr (2026)", "Säule 3b: Flexibel, keine Beitragslimite", "Erwerbsunfähigkeit: Schutz bei Invalidität"], speakText: "Lebensversicherungen schützen das Leben und die Vorsorge. Die Säule 3a bietet Steuervorteile bis 7'258 Franken pro Jahr." },
    { title: "Krankenversicherung", content: "Grundversicherung und Zusätze:", bulletPoints: ["KVG Grundversicherung: Obligatorisch, Aufnahmepflicht", "Franchise: CHF 300 bis CHF 2'500 wählbar", "Zusatzversicherungen (VVG): Spital, Alternativmedizin, Zahn", "KTG: Krankentaggeld bei Arbeitsunfähigkeit (80% Lohn)", "Wichtig: Zusatz VOR Kassenwechsel abschliessen!", "Gesundheitsprüfung bei Zusatzversicherungen"], speakText: "Die KVG Grundversicherung ist obligatorisch mit Aufnahmepflicht. Zusatzversicherungen unterliegen dem VVG und die Kasse darf ablehnen." },
    { title: "Unfallversicherung (UVG)", content: "Obligatorisch für Arbeitnehmende:", bulletPoints: ["Berufsunfall (BU): Prämie zahlt Arbeitgeber", "Nichtberufsunfall (NBU): Prämie zahlt Arbeitnehmer", "NBU erst ab 8 Wochenstunden beim gleichen AG", "Leistung: 80% des Lohns als Taggeld, KEINE Franchise", "Höchstversicherter Lohn 2026: CHF 148'200", "UVG-Lücke bei hohen Löhnen: Zusatzversicherung nötig"], speakText: "Die UVG Unfallversicherung ist obligatorisch. Sie zahlt 80 Prozent des Lohns ohne Franchise. Der Höchstlohn beträgt 148'200 Franken." },
  ] } },
  { id: "t4-2", title: "Sachversicherungen Überblick", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Gebäude und Hausrat", content: "Schutz für Heim und Besitz:", bulletPoints: ["Gebäudeversicherung: 19 Kantone Monopol, 7 GUSTAVO frei", "GUSTAVO = Genf, Uri, Schwyz, Tessin, AI, Wallis, Obwalden", "Hausratversicherung: Alles Bewegliche im Haushalt", "Gedeckt: Feuer, Einbruch, Wasser, Elementar", "Neuwert vs. Zeitwert - immer klären!", "Unterversicherung = proportionale Kürzung!"], speakText: "Die Gebäudeversicherung ist in 19 Kantonen ein Monopol. In den 7 GUSTAVO-Kantonen kannst du als Vermittler aktiv werden." },
    { title: "Haftpflicht", content: "Wenn du anderen Schaden zufügst:", bulletPoints: ["Privathaftpflicht: Nicht obligatorisch, aber wichtig!", "Typische Deckung: CHF 5-10 Mio.", "Betriebshaftpflicht: Für Unternehmen", "Berufshaftpflicht: Für beratende Berufe", "Produkthaftpflicht: Für Hersteller/Lieferanten", "D&O: Organhaftpflicht für Geschäftsleitung"], speakText: "Die Privathaftpflicht ist nicht obligatorisch aber dringend empfohlen. Die typische Deckungssumme beträgt 5 bis 10 Millionen Franken." },
    { title: "Motorfahrzeug", content: "Versicherung fürs Auto:", bulletPoints: ["MF-Haftpflicht: Obligatorisch (min. CHF 5 Mio. Personenschaden)", "Teilkasko: Feuer, Diebstahl, Glasbruch, Elementar", "Vollkasko: + selbst verschuldete Kollision", "Bonussystem: Bis 70% Rabatt für schadenfreie Jahre", "Insassenunfall, Pannenhilfe als Zusätze", "E-Mobilität: Spezialdeckung für Akku und Ladestation"], speakText: "Die MF-Haftpflicht ist obligatorisch mit mindestens 5 Millionen Deckung. Teilkasko und Vollkasko sind freiwillig." },
  ] } },
  { id: "t4-3", title: "Unsere Versicherungspartner", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Mit wem wir arbeiten", content: "Unsere wichtigsten Partner:", bulletPoints: ["Helvetia: Stark in Sach, Haftpflicht, MF", "Zurich: Umfassendes Portfolio, Cyber-Versicherung", "Swiss Life: Marktführer Lebensversicherung/Vorsorge", "AXA: Grösster Allbranchenversicherer (CHF 6.6 Mrd.)", "Mobiliar: Genossenschaft, stark im Schadengeschäft", "CSS: Spezialist Krankenversicherung", "Baloise: Tradition, Privat- und KMU-Kunden", "Allianz: Leben und Vorsorge, international"], speakText: "Wir arbeiten mit den führenden Schweizer Versicherern zusammen. Von Helvetia über Swiss Life bis AXA - für jeden Kundenbedarf der passende Partner." },
    { title: "Warum ungebunden?", content: "Dein Vorteil als ungebundener Vermittler:", bulletPoints: ["Freie Produktwahl aus allen Partnern", "Immer die beste Lösung für den Kunden", "Keine Verkaufsquoten eines einzelnen Versicherers", "Vergleichsangebote von mehreren Anbietern", "Höheres Kundenvertrauen durch Unabhängigkeit", "Langfristige Kundenbeziehungen statt Einmalverkäufe"], speakText: "Als ungebundener Vermittler wählst du frei aus allen Partnern. Das bedeutet immer die beste Lösung für den Kunden und höheres Vertrauen." },
  ] } },
  { id: "t4-4", title: "Quiz: Produkte", type: "quiz", duration: "15 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
    { text: "Was ist der Höchstlohn UVG 2026?", options: ["CHF 100'000", "CHF 126'000", "CHF 148'200", "CHF 200'000"], correctIndex: 2, explanation: "Der UVG-Höchstversichertenlohn beträgt CHF 148'200 (2026)." },
    { text: "Was bedeutet GUSTAVO?", options: ["Ein Versicherungsprodukt", "7 Kantone ohne Gebäudeversicherungsmonopol", "Eine Prämienformel", "Ein Versicherer"], correctIndex: 1, explanation: "GUSTAVO = Genf, Uri, Schwyz, Tessin, AI, Wallis, Obwalden." },
    { text: "Ist die Privathaftpflicht obligatorisch?", options: ["Ja", "Nein, aber dringend empfohlen", "Nur für Unternehmen", "Nur in der Westschweiz"], correctIndex: 1, explanation: "Die Privathaftpflicht ist nicht obligatorisch, wird aber dringend empfohlen." },
    { text: "Was deckt die Vollkasko ZUSÄTZLICH zur Teilkasko?", options: ["Diebstahl", "Selbst verschuldete Kollision", "Glasbruch", "Elementarschäden"], correctIndex: 1, explanation: "Vollkasko = Teilkasko + selbst verschuldete Kollisionsschäden." },
    { text: "Grösster Allbranchenversicherer der Schweiz?", options: ["Mobiliar", "Helvetia", "AXA", "Baloise"], correctIndex: 2, explanation: "AXA ist der grösste Allbranchenversicherer mit CHF 6.6 Mrd. Prämienvolumen." },
    { text: "Ab wann gilt die NBU-Versicherung (UVG)?", options: ["Ab 4h/Woche", "Ab 8h/Woche", "Ab 20h/Woche", "Immer"], correctIndex: 1, explanation: "Die NBU-Versicherung gilt ab 8 Wochenstunden beim gleichen Arbeitgeber." },
  ] } },
] };
export default m;
