import type { Modul } from "../../lernpfade-data";
const m: Modul = { id: "t5", title: "Tools und Systeme", description: "CRM, Vergleichstools, Datenschutz", credits: 20, lektionen: [
  { id: "t5-1", title: "Dein digitaler Arbeitsplatz", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Tools für den Alltag", content: "Diese Tools wirst du täglich nutzen:", bulletPoints: ["CRM-System: Kundendaten, Termine, Aufgaben, Gesprächsnotizen", "Vergleichsrechner: Prämien verschiedener Anbieter in Sekunden vergleichen", "Offertentool: Professionelle Offerten per Knopfdruck erstellen", "E-Signatur: Verträge digital unterschreiben lassen (rechtsverbindlich)", "Zuriva Academy: Weiterbildung und Wissenstests", "Aura KI: Dein KI-Assistent für Fachfragen rund um die Uhr"], speakText: "Du arbeitest täglich mit dem CRM-System für Kundendaten, dem Vergleichsrechner für Prämien, dem Offertentool und der E-Signatur. Dazu die Zuriva Academy und Aura als KI-Assistent.", image: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=1200&q=80" },
    { title: "Der digitale Beratungsprozess", content: "So läuft eine moderne Beratung ab:", bulletPoints: ["1. Vorbereitung: Kundendaten im CRM prüfen vor dem Termin", "2. Bedarfsanalyse: Fragebogen digital ausfüllen mit dem Kunden", "3. Vergleich: 3-5 Anbieter in Sekunden vergleichen", "4. Offerte: Professionell gestaltet, per E-Mail oder vor Ort zeigen", "5. Abschluss: E-Signatur oder Papierunterzeichnung", "6. Nachbetreuung: Follow-up Reminder im CRM setzen"], speakText: "Der digitale Beratungsprozess hat 6 Schritte: Vorbereitung im CRM, Bedarfsanalyse, Prämienvergleich, Offerte, Abschluss per E-Signatur und Nachbetreuung mit CRM-Reminder.", image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80" },
  ] } },
  { id: "t5-2", title: "Datenschutz DSG", type: "slides", duration: "20 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Das revidierte DSG", content: "Seit dem 1. September 2023 gilt das neue Datenschutzgesetz:", bulletPoints: ["Gilt für alle die Personendaten bearbeiten", "Personendaten nur für den vereinbarten Zweck verwenden", "Daten nur so lange aufbewahren wie nötig", "Auskunftsrecht: Jeder Kunde kann seine Daten einsehen", "Datenschutzverletzungen müssen dem EDÖB gemeldet werden", "Verstösse: Bussen bis CHF 250'000 möglich!"], speakText: "Das revidierte Datenschutzgesetz gilt seit September 2023. Personendaten dürfen nur zweckgebunden verwendet werden. Der Kunde hat jederzeit Auskunftsrecht. Verstösse können mit bis zu 250'000 Franken gebüsst werden.", image: "https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=1200&q=80" },
    { title: "Praktische Datenschutz-Tipps", content: "So schützt du dich und deine Kunden:", bulletPoints: ["Laptop immer sperren wenn du den Platz verlässt (Win+L)", "Kundendaten NIE per unverschlüsselter E-Mail senden", "Passwörter: Mindestens 12 Zeichen, regelmässig ändern, nie teilen", "Papierdokumente shreddern, nicht ins Altpapier", "Mobile Geräte mit PIN oder Fingerabdruck schützen", "Bildschirm abdecken in Zügen und Cafés"], speakText: "Sperre deinen Laptop immer wenn du weggehst. Sende Kundendaten nie unverschlüsselt. Verwende starke Passwörter. Shreddere Papierdokumente. Schütze mobile Geräte mit PIN.", image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=1200&q=80" },
  ] } },
  { id: "t5-3", title: "Quiz: Tools und Datenschutz", type: "quiz", duration: "10 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
    { text: "Welches Tool nutzt du für die Kundenverwaltung?", options: ["Excel", "CRM-System", "WhatsApp", "Notizblock"], correctIndex: 1, explanation: "Slide 'Tools': CRM-System für Kundendaten, Termine und Aufgaben." },
    { text: "Wie viele Schritte hat der digitale Beratungsprozess?", options: ["3", "4", "6", "8"], correctIndex: 2, explanation: "Slide 'Beratungsprozess': 6 Schritte von Vorbereitung bis Nachbetreuung." },
    { text: "Was ist der erste Schritt im Beratungsprozess?", options: ["Offerte erstellen", "Vertrag unterschreiben", "Kundendaten im CRM prüfen", "Vergleich starten"], correctIndex: 2, explanation: "Slide 'Beratungsprozess': Schritt 1 = Vorbereitung im CRM." },
    { text: "Seit wann gilt das revidierte DSG?", options: ["2020", "1. September 2023", "2025", "2026"], correctIndex: 1, explanation: "Slide 'DSG': Seit dem 1. September 2023." },
    { text: "Wie hoch können DSG-Bussen sein?", options: ["CHF 10'000", "CHF 50'000", "CHF 250'000", "CHF 1 Mio."], correctIndex: 2, explanation: "Slide 'DSG': Bussen bis CHF 250'000." },
    { text: "Was darfst du NICHT per unverschlüsselter E-Mail senden?", options: ["Termine", "Kundendaten", "Wetterberichte", "Offerten-Links"], correctIndex: 1, explanation: "Slide 'Datenschutz-Tipps': Kundendaten NIE unverschlüsselt senden." },
  ] } },
] };
export default m;
