import type { Modul } from "../../lernpfade-data";
const m: Modul = { id: "sv1", title: "Gebäudeversicherung vertieft", description: "Kantonale Systeme, GUSTAVO, Wertermittlung, Elementarschäden", credits: 30, lektionen: [
  { id: "sv1-1", title: "Kantonale Systeme im Detail", type: "slides", duration: "30 Min.", completed: false, content: { type: "slides", slides: [
    { title: "19 Monopolkantone", content: "Hier gilt das kantonale Monopol:", bulletPoints: ["Zürich (GVZ), Bern (GVB), Luzern, Aargau, St. Gallen etc.", "Obligatorische Versicherung bei der kantonalen Anstalt", "Feuer und Elementar in der Grunddeckung", "Prämien oft günstiger als in GUSTAVO (kein Gewinnzuschlag)", "Als Vermittler: KEIN Geschäft in Monopolkantonen möglich", "Aber: Zusatzdeckungen (Erdbeben, Wasser) privat möglich"], speakText: "In 19 Kantonen gibt es ein Monopol der kantonalen Gebäudeversicherung. Dort ist für Vermittler kein Geschäft möglich. Zusatzdeckungen können aber privat vermittelt werden." },
    { title: "7 GUSTAVO-Kantone vertieft", content: "Hier bist du als Vermittler gefragt:", bulletPoints: ["Genf (GE): Versicherung nicht obligatorisch, grosser Markt", "Uri (UR): Obligatorisch, aber bei Privatversicherern", "Schwyz (SZ): Obligatorisch bei Privatversicherern", "Tessin (TI): Nicht obligatorisch", "Appenzell Innerrhoden (AI): Nicht obligatorisch (Ausnahme Oberegg)", "Wallis (VS): Nicht obligatorisch", "Obwalden (OW): Obligatorisch bei Privatversicherern"], speakText: "In den GUSTAVO-Kantonen bist du als Vermittler aktiv. In Uri, Schwyz und Obwalden ist die Versicherung obligatorisch bei Privatversicherern. In Genf, Tessin, AI und Wallis ist sie freiwillig." },
    { title: "Gedeckte Gefahren", content: "Was die Gebäudeversicherung abdeckt:", bulletPoints: ["Feuer: Brand, Blitzschlag, Explosion, Implosion", "Elementar: Hochwasser, Überschwemmung, Sturm (ab 75 km/h)", "Elementar: Hagel, Schneedruck, Felssturz, Erdrutsch, Lawinen", "NICHT gedeckt: Erdbeben (separater Zusatz nötig!)", "NICHT gedeckt: Krieg, Kernenergie, Terrorismus", "NICHT gedeckt: Normale Abnutzung, Alterung, Unterhaltsmängel"], speakText: "Gedeckt sind Feuer und Elementarschäden wie Hochwasser, Sturm und Hagel. Erdbeben sind meist nicht in der Grunddeckung und brauchen einen separaten Zusatz." },
    { title: "Erdbeben-Zusatzversicherung", content: "Ein oft vergessenes Risiko:", bulletPoints: ["Schweiz ist erdbebengefährdet! (Wallis, Basel, Graubünden)", "Gebäudeversicherung deckt Erdbeben NICHT", "Erdbeben-Pool: Freiwillige Branchenlösung der Versicherer", "Max. Deckung Pool: CHF 2 Mrd. pro Ereignis", "Private Erdbebenversicherung: Zusätzlich empfohlen", "Beratungspflicht: Kunden auf Erdbeben-Risiko hinweisen!"], speakText: "Die Schweiz ist erdbebengefährdet, besonders das Wallis und die Region Basel. Die Gebäudeversicherung deckt Erdbeben nicht. Eine Zusatzversicherung ist dringend empfohlen." },
  ] } },
  { id: "sv1-2", title: "Wertermittlung und Prämie", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Wertarten im Detail", content: "Korrekte Bewertung ist entscheidend:", bulletPoints: ["Neuwert: Kosten für Wiederherstellung gleicher Art und Güte", "Zeitwert: Neuwert minus Altersentwertung", "Amtlicher Wert: Steuerlicher Wert (oft viel tiefer!)", "Gebäudeversicherungswert: Vom Kanton festgelegt", "Schätzung: Regelmässig aktualisieren (alle 5-10 Jahre)", "Baupreisindex: Jährliche Anpassung der Versicherungssumme"], speakText: "Die korrekte Wertermittlung ist entscheidend. Der Neuwert, Zeitwert und amtliche Wert können stark voneinander abweichen. Die Versicherungssumme sollte regelmässig aktualisiert werden." },
    { title: "Unterversicherung vermeiden", content: "Das grösste Risiko für den Kunden:", bulletPoints: ["Unterversicherung: VS < tatsächlicher Wert", "Folge: Proportionale Leistungskürzung!", "Beispiel: Wert 1 Mio., versichert 500'000 = 50%", "Schaden 200'000 → Zahlung nur 100'000!", "Erste-Risiko-Deckung: Volle Leistung bis zur Limite", "Deine Pflicht: Kunden regelmässig auf Wertanpassung hinweisen"], speakText: "Unterversicherung führt zu proportionaler Leistungskürzung. Beispiel: Bei 50 Prozent Unterversicherung zahlt der Versicherer bei einem Schaden von 200'000 Franken nur 100'000." },
    { title: "Prämienfaktoren", content: "Was die Prämie bestimmt:", bulletPoints: ["Standort: Gefahrenzone (Hochwasser, Sturm, Hagel)", "Bauweise: Massiv günstiger als Holz", "Baujahr: Ältere Gebäude oft teurer", "Nutzung: Wohnen günstiger als Gewerbe", "Sicherheit: Alarmanlage, Sprinkler = Rabatt", "Selbstbehalt: Höherer SB = tiefere Prämie"], speakText: "Die Prämie wird durch Standort, Bauweise, Baujahr, Nutzung, Sicherheitsmassnahmen und Selbstbehalt bestimmt." },
  ] } },
  { id: "sv1-3", title: "Quiz: Gebäudeversicherung", type: "quiz", duration: "15 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
    { text: "In welchen GUSTAVO-Kantonen ist die Gebäudeversicherung obligatorisch?", options: ["Genf, Tessin, Wallis", "Uri, Schwyz, Obwalden", "Alle GUSTAVO", "Keiner"], correctIndex: 1, explanation: "In Uri, Schwyz und Obwalden ist sie obligatorisch bei Privatversicherern." },
    { text: "Was deckt die Gebäudeversicherung NICHT?", options: ["Feuer", "Hagel", "Erdbeben", "Sturm"], correctIndex: 2, explanation: "Erdbeben sind in der Grunddeckung nicht enthalten." },
    { text: "Was passiert bei 50% Unterversicherung und CHF 200'000 Schaden?", options: ["Volle Zahlung", "CHF 100'000 Zahlung", "CHF 150'000 Zahlung", "Keine Zahlung"], correctIndex: 1, explanation: "Proportionale Kürzung: 50% von 200'000 = 100'000." },
    { text: "Ab welcher Windstärke gilt Sturm?", options: ["50 km/h", "75 km/h", "100 km/h", "120 km/h"], correctIndex: 1, explanation: "Sturm wird in der Versicherung ab 75 km/h definiert." },
    { text: "Welche Region ist besonders erdbebengefährdet?", options: ["Mittelland", "Wallis und Basel", "Tessin", "Ostschweiz"], correctIndex: 1, explanation: "Das Wallis und die Region Basel sind die am stärksten erdbebengefährdeten Gebiete." },
  ] } },
] };
export default m;
