import type { Modul } from "../../lernpfade-data";
const m: Modul = { id: "sv2", title: "Hausrat und Haftpflicht vertieft", description: "Deckung, Ausschlüsse, Praxisfälle, Beratung", credits: 30, lektionen: [
  { id: "sv2-1", title: "Hausratversicherung Praxis", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Deckungsumfang", content: "Was genau versichert ist:", bulletPoints: ["Alle beweglichen Sachen im Haushalt (Neuwert)", "Wertsachen: Schmuck, Uhren, Kunst (oft Sublimit CHF 20'000-50'000)", "Bargeld: Gedeckt bis ca. CHF 2'000-5'000", "Einbruchdiebstahl: Nur mit Einbruchspuren!", "Einfacher Diebstahl auswärts: Oft als Zusatz", "Glasbruch: Mobiliar, Ceranfeld, Dusche (oft separat)"], speakText: "Die Hausratversicherung deckt alle beweglichen Sachen zum Neuwert. Wertsachen haben oft ein Sublimit. Einbruchdiebstahl braucht Einbruchspuren." },
    { title: "Häufige Schadenfälle", content: "Was du in der Praxis erlebst:", bulletPoints: ["Wasserschaden: Waschmaschine, Geschirrspüler, Rohrbruch", "Einbruch: Fenster aufgehebelt, Tür aufgebrochen", "Brand: Kerze, Küche, Elektrogerät", "Elementar: Überschwemmung im Keller nach Gewitter", "Glasbruch: Cerankochfeld, Duschkabine, Mobiliar", "Diebstahl Velo: Oft gedeckt wenn angeschlossen"], speakText: "Häufige Schadenfälle sind Wasserschäden durch Waschmaschinen, Einbrüche, Brände und Elementarschäden wie Überschwemmungen im Keller." },
  ] } },
  { id: "sv2-2", title: "Haftpflichtversicherung Praxis", type: "slides", duration: "30 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Verschuldenshaftung vertieft", content: "Art. 41 OR - Die Grundregel:", bulletPoints: ["Wer einem anderen widerrechtlich Schaden zufügt", "Sei es durch Absicht oder Fahrlässigkeit", "Ist zum Ersatz des Schadens verpflichtet", "Fahrlässigkeit: Sorgfaltspflicht verletzt", "Grobfahrlässigkeit: Offensichtliche Sorgfaltsverletzung", "Vorsatz: Absichtliche Schadenverursachung (nicht versicherbar!)"], speakText: "Art. 41 OR regelt die Verschuldenshaftung. Wer fahrlässig oder vorsätzlich einen Schaden verursacht, muss Ersatz leisten. Vorsatz ist nicht versicherbar." },
    { title: "Kausalhaftung", content: "Haftung OHNE Verschulden:", bulletPoints: ["Tierhalter (Art. 56 OR): Hund beisst Passanten", "Werkeigentümer (Art. 58 OR): Dachziegel fällt auf Auto", "Geschäftsherr (Art. 55 OR): Mitarbeiter verursacht Schaden", "Fahrzeughalter (SVG): Unfall mit Auto", "Familienoberhaupt (Art. 333 ZGB): Kind verursacht Schaden", "Keine Schuld nötig - es reicht der kausale Zusammenhang"], speakText: "Bei der Kausalhaftung haftet man ohne Verschulden. Beispiele: Tierhalter, Werkeigentümer, Geschäftsherr und Fahrzeughalter." },
    { title: "Privathaftpflicht Deckung", content: "Was gedeckt ist und was nicht:", bulletPoints: ["Gedeckt: Personenschäden (Heilungskosten, Schmerzensgeld)", "Gedeckt: Sachschäden (Beschädigung fremder Sachen)", "Gedeckt: Vermögensfolgeschäden (Lohnausfall des Geschädigten)", "NICHT gedeckt: Schäden am eigenen Eigentum", "NICHT gedeckt: Motorfahrzeug-Haftpflicht (eigene Police)", "NICHT gedeckt: Vorsätzlich verursachte Schäden"], speakText: "Die Privathaftpflicht deckt Personen-, Sach- und Vermögensfolgeschäden gegenüber Dritten. Eigenes Eigentum, Motorfahrzeuge und Vorsatz sind nicht gedeckt." },
  ] } },
  { id: "sv2-3", title: "Beratung Hausrat + Haftpflicht", type: "text", duration: "20 Min.", completed: false, content: { type: "text", paragraphs: [
    "Die Kombination Hausrat + Haftpflicht ist oft das Einstiegsprodukt bei neuen Kunden. So berätst du optimal:",
    "Versicherungssumme Hausrat: Faustformel CHF 1'000 pro Quadratmeter Wohnfläche. 80m²-Wohnung = ca. CHF 80'000. Wertsachen separat auflisten!",
    "Deckungssumme Haftpflicht: Mindestens CHF 5 Mio. empfehlen. Personenschäden können Millionen kosten (lebenslange Rente an Geschädigten). CHF 10 Mio. ist Standard bei guten Anbietern.",
    "Kombinierte Policen: Viele Versicherer bieten Hausrat + Haftpflicht als Kombi an. Oft günstiger als einzeln. Beispiel: AXA 'Haushalt Kombi', Mobiliar 'Hausratversicherung mit Haftpflicht'.",
    "Cross-Selling: Wer Hausrat/Haftpflicht hat, braucht oft auch: Rechtsschutzversicherung, Reiseversicherung, Wertsachenversicherung. Frage aktiv danach!",
  ] } },
  { id: "sv2-4", title: "Quiz: Hausrat und Haftpflicht", type: "quiz", duration: "15 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
    { text: "Was ist bei Einbruchdiebstahl zwingend für die Deckung?", options: ["Polizeibericht", "Einbruchspuren", "Zeugen", "Videoaufnahme"], correctIndex: 1, explanation: "Einbruchspuren müssen vorhanden sein." },
    { text: "Welche Haftungsart greift bei einem Hundebiss?", options: ["Verschuldenshaftung", "Kausalhaftung (Tierhalterhaftung)", "Vertragshaftung", "Keine"], correctIndex: 1, explanation: "Tierhalter haften kausal nach Art. 56 OR." },
    { text: "Faustformel Versicherungssumme Hausrat?", options: ["CHF 500/m²", "CHF 1'000/m²", "CHF 2'000/m²", "CHF 5'000/m²"], correctIndex: 1, explanation: "Faustformel: CHF 1'000 pro Quadratmeter Wohnfläche." },
    { text: "Welche Mindest-Deckungssumme bei der Haftpflicht empfehlen?", options: ["CHF 1 Mio.", "CHF 5 Mio.", "CHF 100'000", "CHF 500'000"], correctIndex: 1, explanation: "Mindestens CHF 5 Mio., besser CHF 10 Mio." },
  ] } },
] };
export default m;
