import type { Modul } from "../../lernpfade-data";
const m: Modul = { id: "sv3", title: "Motorfahrzeugversicherung vertieft", description: "Haftpflicht, Kasko, Bonus, Zusatzdeckungen, E-Mobilität", credits: 30, lektionen: [
  { id: "sv3-1", title: "MF-Haftpflicht und Kasko", type: "slides", duration: "30 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Obligatorische MF-Haftpflicht", content: "Gesetzliche Grundlage SVG Art. 63:", bulletPoints: ["Obligatorisch für jedes zugelassene Fahrzeug", "Mindestdeckung: CHF 5 Mio. Personen, CHF 1 Mio. Sachen", "Die meisten Versicherer: CHF 100 Mio. Pauschaldeckung", "Deckt Schäden an DRITTEN (nicht am eigenen Fahrzeug)", "Fahrzeugausweis wird nur mit Versicherungsnachweis ausgestellt", "Grüne Karte (Carte Verte): Nachweis für Auslandsreisen"], speakText: "Die MF-Haftpflicht ist obligatorisch. Mindestdeckung 5 Millionen für Personen. Die meisten Versicherer bieten 100 Millionen Pauschaldeckung." },
    { title: "Teilkasko", content: "Freiwilliger Schutz für dein Fahrzeug:", bulletPoints: ["Feuer, Explosion, Blitzschlag", "Diebstahl des Fahrzeugs oder von Fahrzeugteilen", "Glasbruch (Windschutzscheibe, Seitenscheiben)", "Elementarschäden: Hagel, Sturm, Überschwemmung", "Kollision mit Tieren (Wildunfall)", "Marderbiss an Kabeln und Schläuchen", "Böswillige Beschädigung durch Dritte (Vandalismus)"], speakText: "Die Teilkasko deckt Feuer, Diebstahl, Glasbruch, Elementarschäden, Wildunfall und Marderbiss." },
    { title: "Vollkasko", content: "Teilkasko PLUS:", bulletPoints: ["Alles was die Teilkasko deckt", "PLUS: Selbst verschuldete Kollisionsschäden", "Empfohlen für: Neuwagen, Leasing, wertvolle Fahrzeuge", "Ab wann auf Teilkasko wechseln? Faustformel: Fahrzeugwert < CHF 15'000", "Selbstbehalt Teilkasko: Oft CHF 200-500", "Selbstbehalt Vollkasko: Oft CHF 500-1'000"], speakText: "Die Vollkasko deckt zusätzlich selbst verschuldete Kollisionsschäden. Empfohlen für Neuwagen und Leasing-Fahrzeuge." },
  ] } },
  { id: "sv3-2", title: "Bonussystem und Zusätze", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Das Bonussystem", content: "Belohnung für schadenfreies Fahren:", bulletPoints: ["Startbonus: Meist 100% (keine Rabatte)", "Pro schadenfreies Jahr: 1 Bonusstufe runter", "Maximum: Bis 70% Rabatt (Bonusstufe 0)", "Ein Schaden: 3-4 Stufen hoch = deutlich höhere Prämie", "Bonusschutz: Erster Schaden ohne Stufenverlust (Zusatz)", "Zweitwagenrabatt: Tieferer Einstieg wenn 1. Wagen schadenfrei"], speakText: "Das Bonussystem belohnt schadenfreies Fahren mit bis zu 70 Prozent Rabatt. Ein Schaden kostet 3 bis 4 Bonusstufen." },
    { title: "Wichtige Zusatzdeckungen", content: "Was du empfehlen solltest:", bulletPoints: ["Insassenunfallversicherung: Ergänzt UVG für Mitfahrer", "Pannenhilfe/Assistance: Abschleppen, Mietfahrzeug, Weiterreise", "Grobfahrlässigkeit: Leistungskürzung vermeiden!", "Parkschadendeckung: Fremdverschuldete Schäden im Stillstand", "Neupreisentschädigung: Erste 1-3 Jahre zum Neupreis", "E-Mobilität: Akku, Ladestation, Ladekabel, Wallbox"], speakText: "Empfehle Insassenunfall, Pannenhilfe, Grobfahrlässigkeitsdeckung und bei E-Autos die E-Mobilitätsdeckung." },
    { title: "E-Mobilität Spezial", content: "Wachsender Markt:", bulletPoints: ["E-Auto Anteil Schweiz: Steigend, über 25% Neuzulassungen", "Spezialrisiken: Akku (Hauptwert des Fahrzeugs!)", "Ladestation/Wallbox: Beschädigung, Blitzschlag", "Ladekabel: Diebstahl, Beschädigung", "Tiefere Prämien: E-Autos oft günstiger versichert", "Gutes Verkaufsargument für Neukunden mit E-Auto"], speakText: "E-Mobilität ist ein wachsender Markt mit speziellen Versicherungsbedürfnissen für Akku, Ladestation und Ladekabel." },
  ] } },
  { id: "sv3-3", title: "Quiz: Motorfahrzeug", type: "quiz", duration: "15 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
    { text: "Mindestdeckung MF-Haftpflicht Personenschäden?", options: ["CHF 1 Mio.", "CHF 5 Mio.", "CHF 10 Mio.", "CHF 100 Mio."], correctIndex: 1, explanation: "Gesetzliches Minimum: CHF 5 Mio. für Personenschäden." },
    { text: "Was deckt die Teilkasko NICHT?", options: ["Diebstahl", "Glasbruch", "Selbstverschuldete Kollision", "Hagel"], correctIndex: 2, explanation: "Selbstverschuldete Kollision ist nur in der Vollkasko gedeckt." },
    { text: "Maximaler Bonusrabatt?", options: ["30%", "50%", "70%", "90%"], correctIndex: 2, explanation: "Das Maximum liegt bei ca. 70% Rabatt." },
    { text: "Ab welchem Fahrzeugwert auf Teilkasko wechseln?", options: ["CHF 5'000", "CHF 15'000", "CHF 30'000", "CHF 50'000"], correctIndex: 1, explanation: "Faustformel: Ab Fahrzeugwert unter CHF 15'000 auf Teilkasko wechseln." },
    { text: "Was ist das Hauptrisiko bei E-Autos?", options: ["Motor", "Akku", "Reifen", "Software"], correctIndex: 1, explanation: "Der Akku macht den Hauptwert eines E-Autos aus." },
  ] } },
] };
export default m;
