import type { Modul } from "../../lernpfade-data";
const m: Modul = { id: "sv4", title: "Gewerbe und Betrieb", description: "KMU-Versicherung, BU, Cyber, D&O, Transportversicherung", credits: 30, lektionen: [
  { id: "sv4-1", title: "KMU-Versicherungen", type: "slides", duration: "30 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Was jedes KMU braucht", content: "Grundschutz für Unternehmen:", bulletPoints: ["Betriebshaftpflicht: Schäden gegenüber Dritten", "Sachversicherung: Gebäude, Einrichtung, Vorräte", "Betriebsunterbrechung (BU): Ertragsausfall bei Stillstand", "UVG: Obligatorisch für alle Mitarbeitenden", "BVG: Obligatorisch ab CHF 22'680 Lohn", "KTG: Dringend empfohlen (Lohnfortzahlung bei Krankheit)"], speakText: "Jedes KMU braucht Betriebshaftpflicht, Sachversicherung, Betriebsunterbrechung und die obligatorischen Sozialversicherungen." },
    { title: "Betriebsunterbrechung (BU)", content: "Oft unterschätzt:", bulletPoints: ["Deckung: Fixkosten + entgangener Gewinn bei Stillstand", "Auslöser: Feuer, Elementar, Maschinenbruch", "Haftungszeit: 12-24 Monate (Zeitraum der Entschädigung)", "Wartefrist: Typisch 2-5 Tage", "Kalkulation: Jahresumsatz minus variable Kosten", "WICHTIG: Ohne BU kann ein Schaden die Firma ruinieren!"], speakText: "Die Betriebsunterbrechungsversicherung deckt Fixkosten und entgangenen Gewinn bei Betriebsstillstand. Ohne BU kann ein Schaden das Unternehmen ruinieren." },
  ] } },
  { id: "sv4-2", title: "Cyber-Versicherung", type: "slides", duration: "25 Min.", completed: false, content: { type: "slides", slides: [
    { title: "Nr. 1 Risiko weltweit", content: "Cybervorfälle dominieren die Risikolandschaft:", bulletPoints: ["Cybervorfälle sind das Nr. 1 Risiko weltweit (10% Vorsprung)", "Ransomware: Daten verschlüsselt, Lösegeld gefordert", "Phishing: Betrügerische E-Mails zur Datendiebstahl", "Datenleck: Kundendaten gestohlen und veröffentlicht", "Betriebsunterbrechung durch IT-Ausfall", "Durchschnittlicher Schaden KMU: CHF 100'000-500'000"], speakText: "Cybervorfälle sind das Nummer 1 Risiko weltweit. Ransomware, Phishing und Datenlecks können KMU Hunderttausende Franken kosten." },
    { title: "Was die Cyber-Police deckt", content: "Umfassender Schutz:", bulletPoints: ["Eigenschaden: Wiederherstellung von Daten und Systemen", "Drittschaden: Datenschutzverletzung gegenüber Kunden", "Betriebsunterbrechung durch Cyberangriff", "Krisenmanagement: IT-Forensik, PR-Beratung, Rechtsberatung", "Cyber-Erpressung: Lösegeld-Verhandlung", "Bussgelder: Deckung von Datenschutz-Bussen", "WACHSENDER MARKT: Grosses Verkaufspotenzial!"], speakText: "Die Cyber-Versicherung deckt Eigenschäden, Drittschäden, Betriebsunterbrechung und Krisenmanagement. Das ist ein stark wachsender Markt." },
  ] } },
  { id: "sv4-3", title: "D&O und Berufshaftpflicht", type: "text", duration: "20 Min.", completed: false, content: { type: "text", paragraphs: [
    "D&O (Directors & Officers) Versicherung: Schützt Verwaltungsrat und Geschäftsleitung vor persönlicher Haftung. In der Schweiz haften VR-Mitglieder persönlich und unbeschränkt mit ihrem Privatvermögen! Die Prämien sind in den letzten Jahren gestiegen.",
    "Berufshaftpflicht: Pflicht für beratende Berufe. Deckt Vermögensschäden durch falsche Beratung. Beispiel: Du empfiehlst eine zu tiefe Deckungssumme, der Kunde hat einen Schaden → du haftest für die Differenz!",
    "Produkthaftpflicht: Für Hersteller und Importeure. Wenn ein Produkt einen Schaden verursacht, haftet der Hersteller. Auch für importierte Produkte aus dem Ausland!",
    "Transportversicherung: Für Waren auf dem Transportweg. Deckt Beschädigung, Verlust und Diebstahl. Wichtig für Import/Export und E-Commerce.",
    "Dein Verkaufsansatz bei KMU: Erstelle eine Risikoanalyse. Zeige die Deckungslücken auf. Biete ein massgeschneidertes Paket an. Betone: Ein einziger Schaden ohne Versicherung kann das Unternehmen ruinieren.",
  ] } },
  { id: "sv4-4", title: "Quiz: Gewerbe und Betrieb", type: "quiz", duration: "15 Min.", completed: false, content: { type: "quiz", passingScore: 70, questions: [
    { text: "Was deckt die Betriebsunterbrechungsversicherung?", options: ["Maschinenreparatur", "Fixkosten + entgangener Gewinn bei Stillstand", "Mitarbeiterunfälle", "Kundenreklamationen"], correctIndex: 1, explanation: "BU deckt Fixkosten und entgangenen Gewinn." },
    { text: "Was ist das Nr. 1 Risiko weltweit?", options: ["Naturkatastrophen", "Cybervorfälle", "Pandemien", "Krieg"], correctIndex: 1, explanation: "Cybervorfälle mit 10 Prozentpunkten Vorsprung." },
    { text: "Wofür haften VR-Mitglieder in der Schweiz?", options: ["Gar nicht", "Beschränkt auf Firmenvermögen", "Persönlich und unbeschränkt", "Nur bei Vorsatz"], correctIndex: 2, explanation: "VR-Mitglieder haften persönlich und unbeschränkt mit ihrem Privatvermögen." },
    { text: "Was deckt die Produkthaftpflicht?", options: ["Eigene Produkte", "Schäden durch hergestellte/importierte Produkte", "Ladendiebstahl", "Patente"], correctIndex: 1, explanation: "Schäden die durch hergestellte oder importierte Produkte verursacht werden." },
  ] } },
] };
export default m;
